/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Welcher Stand läuft gerade */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Wer fragt
         * @description Beantwortet, was das mitgeschickte Token beweist — und nicht mehr.
         *     Ohne Token ist `angemeldet` false; das ist kein Fehler, sondern die
         *     Antwort. Die Demo-Haushalte sind ohne Anmeldung sichtbar.
         */
        get: operations["getIch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verfügbare Haushalte
         * @description Bis zum Datenmodell (T5) sind das die Beispielhaushalte aus dem Repo.
         *     Die Form der Antwort ändert sich dadurch nicht.
         */
        get: operations["listHaushalte"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/plan/{woche}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wochenplan eines Haushalts */
        get: operations["getWochenplan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/einladungen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Jemanden einladen
         * @description Erzeugt einen einmalig gültigen Code. Nur planende Personen dürfen das.
         *
         *     Die Rolle wird beim Einladen festgelegt und nicht beim Beitritt: Wer
         *     dazukommt, soll nicht selbst entscheiden, was er im Haushalt darf.
         */
        post: operations["createEinladung"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/einladungen/{code}/annehmen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Einer Einladung folgen
         * @description Verbindet die angemeldete Person mit dem Haushalt aus der Einladung.
         *     Ein Code gilt einmal und läuft ab.
         */
        post: operations["acceptEinladung"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Version: {
            /**
             * @description kurze Commit-Kennung oder "dev"
             * @example f18a432
             */
            version: string;
        };
        /**
         * @description Absichtlich schmal: Hier steht nur, was der Aussteller signiert hat.
         *     Welche Person in welchem Haushalt dahintersteckt, ist eine Frage an die
         *     Datenbank und kommt mit dem Onboarding dazu.
         */
        Ich: {
            angemeldet: boolean;
            /** @description Nutzerkennung des Anmeldedienstes */
            subject?: string | null;
            name?: string | null;
            email?: string | null;
        };
        Fehler: {
            /**
             * @description für Menschen lesbar, deutsch
             * @example die Woche "2026-W99" liegt außerhalb von 1..53
             */
            fehler: string;
        };
        Einladung: {
            /** @example K7MQ2XPD */
            code: string;
            /** @enum {string} */
            rolle: "planend" | "ausfuehrend";
            /** Format: date-time */
            gueltig_bis: string;
        };
        Haushalt: {
            /** @example familie-a */
            id: string;
            /** @example Familie A */
            name: string;
            mitglieder: components["schemas"]["Mitglied"][];
        };
        Mitglied: {
            /** @example m-anna */
            id: string;
            /** @example Anna */
            name: string;
            /**
             * @description `planend` plant und führt aus, `ausfuehrend` führt nur aus,
             *     `betreut` erzeugt Arbeit ohne welche zu übernehmen.
             * @enum {string}
             */
            rolle: "planend" | "ausfuehrend" | "betreut";
        };
        Wochenplan: {
            /** @example 2026-W38 */
            woche: string;
            haushalt: components["schemas"]["Haushalt"];
            aufgaben: components["schemas"]["Aufgabe"][];
            /**
             * @description Die Rolle des Aufrufers in diesem Haushalt. Fehlt bei
             *     Demo-Haushalten und ohne Anmeldung.
             * @enum {string|null}
             */
            meine_rolle?: "planend" | "ausfuehrend" | "betreut" | null;
            /**
             * @description Eine Zeile je Person, die Aufgaben übernehmen kann — **nur für
             *     planende Personen**. Wer ausführt, sieht den ganzen Plan, aber
             *     nicht die Auswertung darüber, wer im Haushalt wie viel trägt.
             *
             *     Fehlt das Feld, ist das kein Fehler: Der Aufrufer darf es nicht
             *     sehen. Demo-Haushalte liefern es mit, sie haben nichts zu
             *     verbergen.
             */
            bilanz?: components["schemas"]["Bilanz"][];
            /**
             * @description Was nicht im Plan steht, mit Grund. Ohne dieses Feld könnte die
             *     App nicht erklären, warum etwas fehlt.
             */
            uebersprungen: components["schemas"]["Uebersprungen"][];
        };
        Aufgabe: {
            /** @example t-bad */
            vorlage_id: string;
            /** @example Bad putzen */
            titel: string;
            kategorie: components["schemas"]["Kategorie"];
            /** @enum {string} */
            art: "ausfuehrung" | "organisation";
            /**
             * Format: date
             * @description Kalendertag ohne Uhrzeit und ohne Zeitzone (ADR-0002). Über die
             *     Grenze geht die ISO-Zeichenkette; die Anzeige rechnet sie in
             *     Europe/Berlin um.
             * @example 2026-09-19
             */
            tag: string;
            /** @enum {string} */
            zeitfenster: "egal" | "morgens" | "abends";
            /** @example 35 */
            dauer_min: number;
            /** @description Planungs- und Erinnerungsaufwand, unabhängig von der Dauer */
            kopflast: number;
            /**
             * @description Kennung des Mitglieds
             * @example m-ben
             */
            zustaendig: string;
            /**
             * Format: date
             * @description gesetzt, wenn die Aufgabe eine echte Frist hat
             */
            frist?: string | null;
            begruendung: components["schemas"]["Begruendung"];
        };
        /**
         * @description Maschinenlesbar. Das Sprachmodell formuliert daraus später einen Satz
         *     für die Oberfläche — es erfindet keine Begründung, es übersetzt eine.
         */
        Begruendung: {
            /** @enum {string} */
            code: "rotation" | "ausgleich" | "feste_person" | "einzige_moeglichkeit" | "frist" | "eigene_aufgabe";
            /** @description bei `rotation` die Person, die die Aufgabe zuletzt hatte */
            zuletzt_bei?: string | null;
        };
        Bilanz: {
            mitglied_id: string;
            minuten: number;
            kopflast: number;
            /** @description Minuten + Kopflast × 15 */
            gewichtet: number;
            /** @description verfügbare Minuten der ganzen Woche */
            kapazitaet_minuten: number;
            /**
             * @description Verplante Minuten im Verhältnis zur verfügbaren Zeit. Gerechnet
             *     wird mit den reinen Minuten — Kopflast kostet Aufmerksamkeit,
             *     aber keine Uhrzeit (ADR-0004).
             */
            auslastung_prozent: number;
            aufgaben: number;
        };
        Uebersprungen: {
            vorlage_id: string;
            titel: string;
            /** @enum {string} */
            grund: "gilt_nicht" | "abgewaehlt" | "nicht_faellig" | "startdichte" | "keine_kapazitaet" | "niemand_geeignet";
        };
        /** @enum {string} */
        Kategorie: "kueche" | "waesche" | "reinigung" | "kind" | "vorrat" | "termine" | "verwaltung" | "wartung" | "sozial" | "aussen";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description die Commit-Kennung des laufenden Dienstes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    getIch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description die Identität des Aufrufers, soweit belegt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ich"];
                };
            };
        };
    };
    listHaushalte: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description alle sichtbaren Haushalte */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Haushalt"][];
                };
            };
        };
    };
    getWochenplan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kennung des Haushalts, z. B. `familie-a` */
                haushaltId: string;
                /** @description ISO-Kalenderwoche, Montag als erster Tag */
                woche: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description der berechnete Plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wochenplan"];
                };
            };
            /** @description die Woche ist nicht lesbar */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    createEinladung: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    rolle: "planend" | "ausfuehrend";
                };
            };
        };
        responses: {
            /** @description der Code */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Einladung"];
                };
            };
            /** @description nur planende Personen dürfen einladen */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    acceptEinladung: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description der Haushalt, zu dem die Person jetzt gehört */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Haushalt"];
                };
            };
            /** @description dafür muss man angemeldet sein */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description den Code gibt es nicht, er ist abgelaufen oder verbraucht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
}
