/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Welcher Stand läuft gerade */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Wer fragt
         * @description Beantwortet, was das mitgeschickte Token beweist — und nicht mehr.
         *     Ohne Token ist `angemeldet` false; das ist kein Fehler, sondern die
         *     Antwort. Die Demo-Haushalte sind ohne Anmeldung sichtbar.
         */
        get: operations["getIch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verfügbare Haushalte
         * @description Die öffentlichen Beispielhaushalte und, wer angemeldet ist, die
         *     eigenen. Nur bei den eigenen ist `meine_rolle` gesetzt — eine Liste
         *     ohne einen solchen Eintrag heißt: dieser Mensch hat noch keinen
         *     Haushalt und gehört ins Onboarding.
         */
        get: operations["listHaushalte"];
        put?: never;
        /**
         * Haushalt einrichten
         * @description Legt einen Haushalt samt Mitgliedern an und macht den Aufrufer darin
         *     planend. Alles in einem Aufruf und in einer Transaktion: Ein
         *     Onboarding, das nach dem zweiten Schritt abbricht, darf keinen halben
         *     Haushalt hinterlassen.
         *
         *     Gefragt wird nur, was der Planer wirklich braucht — Wohnform, Personen
         *     mit grobem Alter, Zeitbudget. Alles Weitere ist Vorgabe und später
         *     änderbar. Eine App gegen Mental Load darf beim Einrichten keine
         *     erzeugen.
         */
        post: operations["createHaushalt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/mitglieder/{mitgliedId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Eine Person ändern
         * @description Den eigenen Namen und die eigene Zeit setzt jeder selbst — wie viel
         *     Zeit jemand hat, weiß nur er. Rolle und Geburtsjahr ändern die
         *     planenden Personen, denn daran hängt, was jemand im Haushalt darf und
         *     welche Aufgaben er überhaupt bekommen kann.
         *
         *     Was fehlt, bleibt stehen. Zurück kommt der ganze Haushalt, damit die
         *     Ansicht nicht raten muss, was sich sonst noch geändert hat.
         */
        patch: operations["updateMitglied"];
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/plan/{woche}/neu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Woche neu rechnen
         * @description Rechnet eine festgeschriebene Woche noch einmal — nach einer Änderung
         *     an den Einstellungen, oder wenn jemand dazugekommen ist.
         *
         *     **Was Spuren hinterlassen hat, bleibt.** Aufgaben mit einem Ereignis —
         *     abgehakt, abgegeben, wieder geöffnet — werden nicht angefasst. Alles
         *     andere war ein Vorschlag und wird ersetzt.
         *
         *     Nur planende Personen: Der Plan gehört dem Haushalt, nicht dem, der
         *     gerade unzufrieden damit ist.
         */
        post: operations["wocheNeuRechnen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/plan/{woche}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wochenplan eines Haushalts */
        get: operations["getWochenplan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte/{haushaltId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Einstellungen des Haushalts ändern
         * @description Nur planende Personen. Was hier steht, entscheidet, welche Aufgaben es
         *     im Haushalt überhaupt gibt — „kein Garten" nimmt das Rasenmähen für
         *     alle aus dem Plan.
         *
         *     Gilt ab der nächsten Woche. Die laufende steht fest (ADR-0008) und
         *     wird nur auf Zuruf neu gerechnet.
         */
        patch: operations["updateHaushalt"];
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/vorlagen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alles, was die App kennt — und was davon bei euch gilt
         * @description Die ganze Bibliothek mit dem Stand dieses Haushalts. Jede Zeile sagt,
         *     ob sie gilt, und wenn nicht, warum: nicht zuständig, noch ungeklärt,
         *     braucht einen Termin, abgewählt.
         *
         *     Der Grund für diese Liste: Ein Plan, dem man nicht widersprechen kann,
         *     ist eine Behauptung. Hier lässt sich jede Zeile umdrehen.
         */
        get: operations["listVorlagen"];
        put?: never;
        /**
         * Eine eigene Aufgabe anlegen
         * @description Für alles, was in der Bibliothek fehlt — die Medikamente der
         *     Großmutter, der Putzplan der WG, das Vereinstraining.
         *
         *     Bewusst wenige Felder: Eine eigene Aufgabe anzulegen ist Dateneingabe,
         *     und Dateneingabe ist das, wogegen das Produkt antritt. Sie ist der
         *     Ausweg für das Fehlende, nicht der Weg.
         *
         *     Die Kopflast wird nicht als Zahl abgefragt, sondern aus zwei Fragen
         *     abgeleitet, die man ohne Kenntnis des Modells beantworten kann.
         */
        post: operations["createEigeneVorlage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/vorlagen/{vorlageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Eine Vorlage abbestellen oder wieder anbestellen
         * @description „Das machen wir nicht" — dauerhaft. Die Vorlage verschwindet aus allen
         *     künftigen Plänen, bis jemand sie wieder anbestellt.
         *
         *     Das ist die einfachste Form der Lernschleife und die wichtigste: Ohne
         *     sie kann der Haushalt dem Vorschlag nur folgen oder ihn jede Woche neu
         *     wegklicken.
         *
         *     Nur planende Personen — es gilt für alle.
         */
        patch: operations["setVorlage"];
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/absprachen/{vorlageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Wochenraster einer Vorlage setzen
         * @description Wer an welchem Wochentag. Alle sieben Plätze auf einmal, Index 0 ist
         *     Montag; ein leerer Eintrag heißt „für diesen Tag ist nichts
         *     abgesprochen".
         *
         *     **Der Planer verteilt diese Aufgaben nicht.** Er verteilt nach
         *     Kapazität — wie viel Zeit jemand hat. Wer ein Kind um 7:45 in die Kita
         *     bringen kann, hängt dagegen am Arbeitsplan, und den kennt die App
         *     nicht. Ohne Absprache würde sie mit voller Überzeugung den Falschen
         *     einteilen; deshalb wird hier nicht geraten, sondern gefragt.
         *
         *     Die Absprache gilt, bis jemand sie ändert — „diese Woche wie letzte"
         *     ist damit der Normalfall. Eine einzelne Ausnahme ist `zuteilen` und
         *     betrifft nur den einen Termin.
         *
         *     Nur planende Personen: Eine Absprache ist eine Vereinbarung über andere
         *     Menschen.
         */
        put: operations["setAbsprache"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/absprachen/{vorlageId}/ab-heute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Die Absprache in die laufende Woche eintragen
         * @description Die laufende Woche steht fest, sobald sie das erste Mal angesehen
         *     wurde. Eine frisch gesetzte Absprache gilt deshalb ab der **nächsten**
         *     Woche von selbst — dieser Aufruf ist der Handgriff für „ab sofort".
         *
         *     Er trägt **nur diese Vorlage** ein und **nur ab heute**. Bewusst nicht
         *     `plan/{woche}/neu`: Das Neurechnen verteilt die ganze Woche neu, und
         *     wer am Mittwoch eine Kita-Absprache einträgt, bekäme nebenbei eine
         *     neue Antwort darauf, wer am Freitag das Bad putzt. Ein Plan, der sich
         *     an Stellen ändert, die niemand angefasst hat, ist der Plan, dem
         *     niemand mehr glaubt.
         *
         *     Was Spuren hinterlassen hat — abgehakt, abgegeben, gestrichen —,
         *     bleibt stehen. Vergangene Tage bleiben unberührt.
         *
         *     Nur planende Personen.
         */
        post: operations["absprachAbHeute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/wochentage/{vorlageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * An welchen Wochentagen eine Aufgabe liegt
         * @description Sieben Plätze, Index 0 ist Montag. **Alle sieben falsch setzt
         *     zurück** — dann gilt wieder der Rhythmus aus der Bibliothek.
         *
         *     Der Fall: Müll rausbringen steht in der Bibliothek auf Dienstag, weil
         *     irgendein Tag dastehen musste. Bei euch kommt die Tonne donnerstags.
         *     Bisher gab es dagegen ein einziges Mittel — die Vorlage abbestellen
         *     und von Hand neu anlegen, womit die Zahlen der Bibliothek verloren
         *     gehen und die Aufgabe als geschätzte „eigene" dasteht.
         *
         *     **Feste Tage schlagen jeden anderen Rhythmus.** Wer „donnerstags"
         *     sagt, meint nicht „alle sieben Tage, bevorzugt donnerstags". Damit
         *     ändert sich auch die Häufigkeit: Aus „alle 14 Tage" wird durch die
         *     Wahl eines Tages „wöchentlich, samstags". Das ist die Aussage und
         *     keine Nebenwirkung — die Oberfläche sagt es beim Setzen dazu.
         *
         *     Nicht für jeden Rhythmus. Beim Auslöser („der Wäschekorb ist voll")
         *     ist ein Wochentag keine Antwort, sondern eine andere Frage; Saison und
         *     Phase laufen über Monate; und was an einem Anlass hängt, hat seinen
         *     Tag schon. Für die gibt es `400`.
         *
         *     Nur planende Personen: Der Tag gilt für alle.
         */
        put: operations["setWochentage"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/rueckmeldungen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Was der Haushalt gemeldet hat
         * @description Nur planende Personen. Melden darf jedes Mitglied, lesen nicht: In der
         *     Liste stehen Sätze über andere Menschen im selben Haushalt, und die
         *     gehören nicht an jede Pinnwand.
         */
        get: operations["listRueckmeldungen"];
        put?: never;
        /**
         * Etwas melden
         * @description **Jedes Mitglied darf melden, nicht nur die planenden.** Die
         *     ausführenden Personen sehen die Stellen, an denen es klemmt, zuerst —
         *     sie bekommen den Plan, den sie nicht gemacht haben. Eine Meldefunktion
         *     nur für Planende meldet, was der Planende ohnehin weiß.
         *
         *     `kontext` sammelt die Oberfläche selbst — Seite, Woche, Fassung. Wer
         *     erst beschreiben muss, wo er gerade war, meldet nichts.
         */
        post: operations["melden"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/anlaesse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Die eingetragenen Anlässe */
        get: operations["listAnlaesse"];
        put?: never;
        /**
         * Einen Anlass eintragen
         * @description Ein Geburtstag, ein Elternabend, ein Termin. Daran hängen die Aufgaben
         *     mit Vorlauf — „Geschenk besorgen, sieben Tage vorher".
         *
         *     Ohne Anlass entsteht keine solche Aufgabe. Die App erfindet keinen
         *     Geburtstag (ADR-0010).
         */
        post: operations["createAnlass"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/anlaesse/{anlassId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Einen Anlass löschen */
        delete: operations["deleteAnlass"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/fakten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Eine Frage zum Haushalt beantworten
         * @description Trägt ein, was der Haushalt hat und was nicht — Pflanzen, Spülmaschine,
         *     Keller. Was hier fehlt, bleibt **unbekannt**, und unbekannt ist nicht
         *     dasselbe wie nein: Unbekanntes wird nicht eingeplant, sondern gefragt.
         *
         *     Zusammengeführt, nicht ersetzt: Eine Antwort löscht die übrigen nicht.
         *
         *     Nur planende Personen. Ein Nein nimmt Aufgaben aus dem Plan aller.
         */
        patch: operations["setFakten"];
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/einladungen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Jemanden einladen
         * @description Erzeugt einen einmalig gültigen Code. Nur planende Personen dürfen das.
         *
         *     Die Rolle wird beim Einladen festgelegt und nicht beim Beitritt: Wer
         *     dazukommt, soll nicht selbst entscheiden, was er im Haushalt darf.
         */
        post: operations["createEinladung"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/aufgaben/{aufgabeId}/erledigt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aufgabe abhaken oder wieder öffnen
         * @description Schreibt ein Ereignis ins Protokoll — keine Spalte auf der Aufgabe.
         *     Eine Spalte kennt nur den letzten Zustand, das Protokoll den Weg
         *     dahin, und die Rotation der Folgewoche liest diesen Weg.
         *
         *     Erlaubt ist es der zuständigen Person und jeder planenden.
         */
        post: operations["setErledigt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/aufgaben/{aufgabeId}/abgeben": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aufgabe zurückgeben
         * @description Gibt die Aufgabe zurück in den Haushalt. Die App sucht nach denselben
         *     Regeln wie beim Zuteilen jemand anderen; findet sie niemanden, steht
         *     die Aufgabe offen da.
         *
         *     Sie verschwindet nicht. Abgeben ist Handlungsmacht, nicht Löschen mit
         *     besserem Gewissen.
         */
        post: operations["aufgabeAbgeben"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/aufgaben/{aufgabeId}/streichen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Einen einzelnen Termin streichen
         * @description Nimmt **diesen einen Termin** aus dem Plan. Die Vorlage bleibt
         *     unangetastet, und ihre übrigen Termine derselben Woche auch: Kommt
         *     „Safiya zur Kita bringen" fünfmal vor, streicht das hier genau einen
         *     Tag.
         *
         *     Der Unterschied zum Abschalten einer Vorlage ist die Reichweite, und er
         *     ist der Grund für diesen Endpunkt: Abschalten gilt für alle künftigen
         *     Wochen. Bis es das Streichen gab, war der einzige Ausweg aus einer
         *     Aufgabe eine Entscheidung über die Zukunft — und ein Fehlgriff nahm
         *     dem Haushalt eine Vorlage weg, die er eigentlich wollte.
         *
         *     Gestrichenes verschwindet aus dem Plan und aus der Bilanz; es steht als
         *     `gestrichen` in der Antwort, damit die App einen Weg zurück anbieten
         *     kann.
         *
         *     Erlaubt ist es der zuständigen Person und jeder planenden.
         */
        post: operations["aufgabeStreichen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/aufgaben/{aufgabeId}/zuteilen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aufgabe von Hand an eine Person geben
         * @description Der Unterschied zu `abgeben`: Dort sucht die App jemanden nach ihren
         *     Regeln, hier hat ein Mensch schon gewählt.
         *
         *     Geprüft wird nur noch, was die Person nicht übernehmen *kann* — Alter,
         *     Rolle, Verteilungsregel der Vorlage, und dass eine eigene Aufgabe der
         *     Person selbst gehört. Was die App nur *bevorzugt* hätte — Rotation,
         *     Auslastung, Kopflast am Tag — gilt hier nicht. Ein Mensch, der es
         *     besser weiß, sticht die Annahmen des Planers.
         *
         *     Jede Korrektur wird als `manual` festgehalten. Sie ist die ehrlichste
         *     Rückmeldung, die das Produkt bekommt: Sie sagt, wo der Planer
         *     danebenlag.
         *
         *     Erlaubt ist es der zuständigen Person und jeder planenden.
         */
        post: operations["aufgabeZuteilen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/einladungen/{code}/annehmen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Einer Einladung folgen
         * @description Verbindet die angemeldete Person mit dem Haushalt aus der Einladung.
         *     Ein Code gilt einmal und läuft ab.
         */
        post: operations["acceptEinladung"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Version: {
            /**
             * @description kurze Commit-Kennung oder "dev"
             * @example f18a432
             */
            version: string;
        };
        /**
         * @description Absichtlich schmal: Hier steht nur, was der Aussteller signiert hat.
         *     Welche Person in welchem Haushalt dahintersteckt, ist eine Frage an die
         *     Datenbank und kommt mit dem Onboarding dazu.
         */
        Ich: {
            angemeldet: boolean;
            /** @description Nutzerkennung des Anmeldedienstes */
            subject?: string | null;
            name?: string | null;
            email?: string | null;
        };
        Fehler: {
            /**
             * @description für Menschen lesbar, deutsch
             * @example die Woche "2026-W99" liegt außerhalb von 1..53
             */
            fehler: string;
        };
        Einladung: {
            /** @example K7MQ2XPD */
            code: string;
            /** @enum {string} */
            rolle: "planend" | "ausfuehrend";
            /** Format: date-time */
            gueltig_bis: string;
            /**
             * @description Name der Person, die dieser Code übernimmt. Fehlt, wenn jemand
             *     Neues dazukommt.
             * @example Asmae
             */
            fuer?: string;
        };
        NeuerHaushalt: {
            /** @example Familie Bauer */
            name: string;
            /**
             * @description Wird zurzeit von keiner Vorlage ausgewertet und deshalb auch nicht
             *     abgefragt — eine Frage, die nichts bewirkt, gehört nicht ins
             *     Onboarding. Das Feld bleibt, weil Wohnform eine echte Eigenschaft
             *     eines Haushalts ist; sobald eine Vorlage daran hängt (Streupflicht,
             *     Dachrinne, Schornsteinfeger), kommt die Frage zurück. Fehlt es,
             *     gilt „wohnung".
             * @enum {string}
             */
            wohnform?: "wohnung" | "haus";
            /**
             * @description Wie viele Zimmer. Filtert nichts, sondern skaliert: Putzaufgaben
             *     dauern in fünf Zimmern länger als in zwei. Fehlt die Angabe, gilt
             *     drei — der Haushalt, für den die Bibliothek kuratiert ist.
             * @example 3
             */
            zimmer?: number;
            /**
             * @description Wie viele Bäder. „Bad putzen" ist pro Bad gerechnet — wer zwei hat,
             *     putzt zwei. Fehlt die Angabe, gilt eins.
             * @example 1
             */
            baeder?: number;
            /** @description Fehlt das Feld, gilt „kein Garten". */
            garten?: boolean;
            /**
             * @description Entscheidet über Aufgaben wie Reifenwechsel oder TÜV. Fehlt das
             *     Feld, gilt „kein Auto", und die Aufgaben entstehen gar nicht erst.
             */
            auto?: boolean;
            haustiere?: string[];
            /**
             * @description Bestimmt, wann ein Tag beginnt und endet. Fehlt sie, wird es
             *     Europe/Berlin — ein Haushalt lebt in einer Zeitzone, nicht in der
             *     Serverzeit. Siehe ADR-0002.
             */
            zeitzone?: string;
            mitglieder: components["schemas"]["NeuesMitglied"][];
        };
        NeuesMitglied: {
            name: string;
            /** @enum {string} */
            rolle: "planend" | "ausfuehrend" | "betreut";
            /**
             * @description Nur bei Kindern nötig; es entscheidet über Altersgrenzen von
             *     Aufgaben. Bei Erwachsenen darf es fehlen — dann gelten sie als
             *     erwachsen und mehr braucht der Planer nicht zu wissen.
             */
            geburtsjahr?: number;
            /**
             * @description Grobes Zeitbudget statt sieben Zahlen. Niemand weiß, wie viele
             *     Minuten Haushalt er dienstags hat; eine erfundene Zahl sieht nur
             *     präziser aus als eine ehrliche Stufe.
             *
             *     Fehlt die Angabe, gilt „mittel"; bei betreuten Personen immer
             *     „keine", egal was hier steht — sie erzeugen Arbeit und übernehmen
             *     keine.
             * @enum {string}
             */
            zeit?: "keine" | "wenig" | "mittel" | "viel";
        };
        Gestrichen: {
            id: string;
            /** @example Bad putzen */
            titel: string;
            /**
             * Format: date
             * @description Der Tag, an dem sie angestanden hätte. Er gehört dazu, weil
             *     gestrichen wird, was an EINEM Tag ansteht — eine Vorlage kann
             *     mehrfach in der Woche vorkommen.
             */
            tag: string;
        };
        Zuteilung: {
            /**
             * @description Name der Person, die die Aufgabe jetzt hat.
             * @example Mia
             */
            zustaendig: string;
        };
        Abgabe: {
            /**
             * @description Name der Person, die übernimmt. Fehlt, wenn niemand geeignet ist —
             *     dann steht die Aufgabe offen im Plan.
             * @example Ben
             */
            uebernimmt?: string;
        };
        /**
         * @description Jedes Feld ist freiwillig. Was fehlt, bleibt stehen — der Unterschied
         *     zwischen „nicht mitgeschickt" und „geleert" ist der ganze Sinn einer
         *     Einstellungsseite.
         */
        HaushaltAenderung: {
            name?: string;
            /** @enum {string} */
            wohnform?: "wohnung" | "haus";
            zimmer?: number;
            baeder?: number;
            garten?: boolean;
            auto?: boolean;
            /** @description Vollständige Liste. Leer heißt „keine mehr". */
            haustiere?: string[];
            zeitzone?: string;
        };
        /** @description Jedes Feld ist freiwillig. Was fehlt, bleibt stehen. */
        MitgliedAenderung: {
            name?: string;
            /** @enum {string} */
            rolle?: "planend" | "ausfuehrend" | "betreut";
            /**
             * @description **0 heißt „kein Geburtsjahr"** und ist bei Erwachsenen die richtige
             *     Antwort — nicht „im Jahr null geboren". Die Betreuungsform wird
             *     daraus neu geraten.
             */
            geburtsjahr?: number;
            /**
             * @description Die grobe Stufe aus dem Onboarding. Der Dienst rechnet sie in
             *     Minuten um; die Minutenwerte stehen nur im Planer, damit es nicht
             *     zwei Vorstellungen davon gibt, was „mittel" bedeutet.
             * @enum {string}
             */
            zeit?: "keine" | "wenig" | "mittel" | "viel";
            /**
             * @description Ausdrücklich gesetzt gewinnt gegen geraten — auch wenn in derselben
             *     Anfrage ein neues Geburtsjahr steht.
             * @enum {string}
             */
            betreuung?: "keine" | "kita" | "schule";
            /**
             * @description Minuten je Wochentag, Index 0 = Montag. Für alle, denen die drei
             *     Stufen zu grob sind. Zusammen mit `zeit` gewinnt diese Angabe.
             */
            minuten?: number[];
        };
        VorlagenStand: {
            /** @example t-pflanzen */
            id: string;
            titel: string;
            kategorie: components["schemas"]["Kategorie"];
            /** @enum {string} */
            art: "ausfuehrung" | "organisation";
            dauer_min: number;
            kopflast: number;
            /**
             * @description Diese Aufgabe verteilt der Planer nicht — sie wird abgesprochen.
             *     Ohne Raster taucht sie mit dem Grund `braucht_absprache` auf.
             */
            braucht_absprache?: boolean;
            /**
             * @description Das Wochenraster, Index 0 = Montag. Leerer Text heißt: für diesen
             *     Tag ist nichts abgesprochen.
             */
            absprache?: string[];
            /**
             * @description An welchen Tagen diese Aufgabe liegt, Index 0 = Montag. Alle
             *     sieben falsch heißt: an keinem festen Tag — der Planer sucht sich
             *     im Fenster einen.
             *
             *     Das ist der **geltende** Stand, nicht der der Bibliothek: Hat der
             *     Haushalt eigene Tage festgelegt, stehen die hier. Ob sie eigene
             *     sind, sagt `wochentage_eigen`.
             */
            wochentage?: boolean[];
            /**
             * @description Die Tage stammen von diesem Haushalt und nicht aus der Bibliothek.
             *     Ohne dieses Feld könnte die Oberfläche „zurücksetzen" nicht von
             *     „nichts zu tun" unterscheiden.
             */
            wochentage_eigen?: boolean;
            /**
             * @description Ob ein Wochentag für diese Aufgabe überhaupt eine Antwort ist.
             *     Falsch beim Auslöser, bei Saison und Phase und bei allem, was an
             *     einem Anlass hängt — dort bietet die Oberfläche die Wahl gar nicht
             *     erst an, statt eine `400` zu provozieren.
             */
            wochentage_moeglich?: boolean;
            /**
             * @description Bei `gilt_nicht`: die fehlende Bedingung als Satz — „Braucht ein
             *     Kind, das zur Schule geht." Fehlt, wenn ein verneintes Faktum die
             *     Ursache ist; dann steht in `frage`, was noch einmal zu fragen
             *     wäre.
             *
             *     Gerechnet im Planer, der die Bedingung ohnehin prüft. Vorher stand
             *     in der Liste nur „gilt bei euch nicht" und daneben eine
             *     Aufzählung aller denkbaren Ursachen — eine Andeutung statt einer
             *     Auskunft.
             * @example Braucht ein Kind, das zur Schule geht.
             */
            voraussetzung?: string;
            /**
             * @description Wie oft sie vorkommt, als Satz: „täglich", „3× pro Woche",
             *     „wöchentlich", „jährlich im Oktober".
             *
             *     Gerechnet im Planer aus dem Rhythmus, nicht in der Oberfläche
             *     nachgebaut — dieselbe Regel wie bei `Mitglied.zeit`. Ohne diese
             *     Angabe fehlte in der Liste die Zahl, die über den Aufwand
             *     entscheidet: „Abendessen kochen, 40 Minuten" ist etwas anderes,
             *     wenn es dreimal die Woche dran ist.
             * @example 3× pro Woche
             */
            haeufigkeit?: string;
            /** @description Ob sie in künftigen Plänen vorkommen kann. */
            aktiv: boolean;
            /**
             * @description Vom Haushalt selbst angelegt. Ihre Zahlen sind geschätzt und tragen
             *     trotzdem die Fairnessrechnung mit — deshalb sind sie sichtbar
             *     gekennzeichnet.
             */
            eigene?: boolean;
            /**
             * @description Warum sie nicht gilt. Fehlt, wenn sie gilt.
             * @enum {string}
             */
            grund?: "gilt_nicht" | "abgewaehlt" | "nicht_faellig" | "startdichte" | "keine_kapazitaet" | "niemand_geeignet" | "unbekannt" | "braucht_termin" | "braucht_absprache";
            /** @description Bei `unbekannt` das Faktum, dessen Antwort fehlt. */
            faktum?: string;
            /**
             * @description Die Frage zu diesem Faktum — mitgeliefert statt nachgeschlagen,
             *     damit die Zeile alles trägt, was sie zum Anzeigen braucht.
             */
            frage?: string;
            /** @description Was eine Antwort mit Ja bringt. */
            dann?: string;
        };
        Anlass: {
            id: string;
            /** @example Geburtstag von Mia */
            titel: string;
            /**
             * Format: date
             * @description Kalendertag ohne Uhrzeit (ADR-0002).
             * @example 2026-11-08
             */
            tag: string;
            /**
             * @description Verbindet den Anlass mit den Vorlagen, die daran hängen. Eine feste
             *     Liste, weil ein freier Text nie zu einer Vorlage passen würde — man
             *     hätte etwas eingetragen und nie erfahren, warum nichts passiert.
             * @enum {string}
             */
            art: "kindergeburtstag" | "geburtstag" | "elternabend" | "arzttermin" | "sonstiges";
            /** @description Geburtstage wiederholen sich, Termine nicht. */
            jaehrlich: boolean;
        };
        NeuerAnlass: {
            titel: string;
            /** Format: date */
            tag: string;
            /** @enum {string} */
            art: "kindergeburtstag" | "geburtstag" | "elternabend" | "arzttermin" | "sonstiges";
            jaehrlich?: boolean;
        };
        NeueVorlage: {
            /** @example Medikamente für Oma sortieren */
            titel: string;
            kategorie: components["schemas"]["Kategorie"];
            /**
             * @description Geschätzt — und die Schätzung trägt die Fairnessrechnung mit. Eine
             *     zu niedrige Zahl verschiebt die Bilanz des ganzen Haushalts, ohne
             *     dass es jemand merkt.
             */
            dauer_min: number;
            /**
             * @description Gewünschter Abstand — täglich, wöchentlich, zweiwöchentlich oder
             *     monatlich.
             * @enum {integer}
             */
            alle_tage: 1 | 7 | 14 | 30;
            /**
             * @description „Muss jemand daran denken, oder sieht man es?" Zählt einfach in die
             *     Kopflast.
             */
            denken?: boolean;
            /**
             * @description „Muss man erst etwas klären — Termin machen, nachsehen, jemanden
             *     fragen?" Zählt doppelt: Ein Termin, den man vereinbaren muss,
             *     kostet mehr Aufmerksamkeit als eine Aufgabe, an die man sich nur
             *     erinnert.
             */
            klaeren?: boolean;
            nur_erwachsene?: boolean;
            /**
             * @description „Muss festgelegt werden, wer wann?" Dann verteilt der Planer die
             *     Aufgabe nicht, sondern fordert ein Wochenraster ein.
             *
             *     Für alles, was am Arbeitsplan hängt statt an freier Zeit — ein
             *     Kind bringen oder abholen, ein Termin, zu dem jemand hin muss. Der
             *     Planer kennt die Kapazität und nicht den Kalender; ohne Absprache
             *     teilt er mit voller Überzeugung den Falschen ein.
             */
            braucht_absprache?: boolean;
        };
        Frage: {
            /** @example pflanzen */
            faktum: string;
            /** @example Habt ihr Pflanzen, die gegossen werden müssen? */
            frage: string;
            /**
             * @description Was eine Antwort mit Ja bringt.
             * @example Dann erinnere ich alle paar Tage ans Gießen.
             */
            dann: string;
        };
        Haushalt: {
            /** @example familie-a */
            id: string;
            /** @example Familie A */
            name: string;
            mitglieder: components["schemas"]["Mitglied"][];
            /**
             * @description Die Rolle des Aufrufers in diesem Haushalt. Fehlt bei den
             *     öffentlichen Beispielhaushalten und überall dort, wo er nicht
             *     Mitglied ist.
             * @enum {string}
             */
            meine_rolle?: "planend" | "ausfuehrend" | "betreut";
            /**
             * @description Kennung des Aufrufers als Person in diesem Haushalt. Damit weiß die
             *     Ansicht, welche Zeile seine eigene ist — etwa in den Einstellungen,
             *     wo jeder seine eigene Zeit setzen darf und sonst nichts.
             */
            ich?: string;
            /** @enum {string} */
            wohnform?: "wohnung" | "haus";
            garten?: boolean;
            auto?: boolean;
            /**
             * @description Garten, Auto und Haustiere entscheiden, welche Aufgaben es im
             *     Haushalt überhaupt gibt — ohne Garten kein Rasen, ohne Auto kein
             *     TÜV. Ohne diese Felder könnten die Einstellungen nicht zeigen, was
             *     angenommen wurde.
             */
            haustiere?: string[];
            zimmer?: number;
            baeder?: number;
        };
        Mitglied: {
            /** @example m-anna */
            id: string;
            /** @example Anna */
            name: string;
            /**
             * @description `planend` plant und führt aus, `ausfuehrend` führt nur aus,
             *     `betreut` erzeugt Arbeit ohne welche zu übernehmen.
             * @enum {string}
             */
            rolle: "planend" | "ausfuehrend" | "betreut";
            /**
             * @description Ob diese Person sich anmelden kann. Steuert, wen man noch einladen
             *     kann — und macht sichtbar, wer bisher nur im Plan steht.
             */
            hat_zugang?: boolean;
            /**
             * @description Fehlt bei Erwachsenen — dort ist „nicht gefragt" die richtige
             *     Antwort und nicht „unbekannt alt" (siehe Member.IsAdult im Planer).
             */
            geburtsjahr?: number;
            /**
             * @description Verfügbare Minuten je Wochentag, Index 0 = Montag. Beim Einrichten
             *     aus einer der drei Stufen geraten und hier korrigierbar. Die Zahlen
             *     tragen die gesamte Verteilung — deshalb stehen sie sichtbar da.
             */
            minuten?: number[];
            /**
             * @description Die Stufe, zu der diese Minuten gehören. **Fehlt, wenn keine
             *     genau passt** — dann hat jemand die Minuten von Hand gesetzt, und
             *     das ist ein eigener gültiger Zustand. Die nächstgelegene Stufe
             *     zurückzugeben wäre eine Behauptung über eine Absicht, die niemand
             *     geäußert hat.
             *
             *     Ausgerechnet wird sie im Planer (`BudgetOf`), nicht in der
             *     Oberfläche: Welche Minuten „mittel" bedeutet, weiß genau eine
             *     Stelle im System. Eine nachgebaute Zuordnung wäre eine zweite
             *     Wahrheit — und die zweite ist immer die, die niemand pflegt.
             * @enum {string}
             */
            zeit?: "keine" | "wenig" | "mittel" | "viel";
            /**
             * @description Beim Einrichten aus dem Alter geraten und hier korrigierbar. An ihr
             *     hängt, welche Aufgaben der Haushalt überhaupt hat — ohne Kita-Kind
             *     keine Kita-Tasche.
             * @enum {string}
             */
            betreuung?: "keine" | "kita" | "schule";
        };
        Wochenplan: {
            /** @example 2026-W38 */
            woche: string;
            haushalt: components["schemas"]["Haushalt"];
            aufgaben: components["schemas"]["Aufgabe"][];
            /**
             * @description Einzelne Termine, die jemand gestrichen hat — nicht Vorlagen. Aus
             *     Plan und Bilanz sind sie raus; hier stehen sie, damit die App einen
             *     Weg zurück anbieten kann. Eine Zeile, die wortlos verschwindet,
             *     lässt jemanden, der sich vertippt hat, ohne Rückweg.
             */
            gestrichen?: components["schemas"]["Gestrichen"][];
            /**
             * @description Die Rolle des Aufrufers in diesem Haushalt. Fehlt bei
             *     Demo-Haushalten und ohne Anmeldung.
             * @enum {string|null}
             */
            meine_rolle?: "planend" | "ausfuehrend" | "betreut" | null;
            /**
             * @description Kennung des Aufrufers als Person in diesem Haushalt. Damit erkennt
             *     die Ansicht, welche Zeile seine ist — und ob er eine Aufgabe
             *     abgeben darf. Fehlt bei Demo-Haushalten und ohne Anmeldung.
             */
            ich?: string;
            /**
             * @description Offene Fragen zum Haushalt — höchstens zwei. Was die App nicht
             *     weiß, plant sie nicht ein; sie fragt danach, und zwar mit dem
             *     Nutzen daneben. Eine Frage ohne erkennbaren Nutzen wird nicht
             *     beantwortet.
             */
            fragen?: components["schemas"]["Frage"][];
            /**
             * @description Eine Zeile je Person, die Aufgaben übernehmen kann — **nur für
             *     planende Personen**. Wer ausführt, sieht den ganzen Plan, aber
             *     nicht die Auswertung darüber, wer im Haushalt wie viel trägt.
             *
             *     Fehlt das Feld, ist das kein Fehler: Der Aufrufer darf es nicht
             *     sehen. Demo-Haushalte liefern es mit, sie haben nichts zu
             *     verbergen.
             */
            bilanz?: components["schemas"]["Bilanz"][];
            /**
             * @description Was nicht im Plan steht, mit Grund. Ohne dieses Feld könnte die
             *     App nicht erklären, warum etwas fehlt.
             */
            uebersprungen: components["schemas"]["Uebersprungen"][];
        };
        Aufgabe: {
            /**
             * @description Kennung der festgeschriebenen Aufgabe. Fehlt bei den öffentlichen
             *     Beispielhaushalten: Deren Wochen werden gerechnet und nicht
             *     geschrieben, es gibt also nichts, woran ein „erledigt" hängen
             *     könnte.
             */
            id?: string;
            /** @description Ob jemand sie abgehakt hat. */
            erledigt?: boolean;
            /** @example t-bad */
            vorlage_id: string;
            /** @example Bad putzen */
            titel: string;
            kategorie: components["schemas"]["Kategorie"];
            /** @enum {string} */
            art: "ausfuehrung" | "organisation";
            /**
             * Format: date
             * @description Kalendertag ohne Uhrzeit und ohne Zeitzone (ADR-0002). Über die
             *     Grenze geht die ISO-Zeichenkette; die Anzeige rechnet sie in
             *     Europe/Berlin um.
             * @example 2026-09-19
             */
            tag: string;
            /** @enum {string} */
            zeitfenster: "egal" | "morgens" | "abends";
            /** @example 35 */
            dauer_min: number;
            /** @description Planungs- und Erinnerungsaufwand, unabhängig von der Dauer */
            kopflast: number;
            /**
             * @description Kennung des Mitglieds. Leer, wenn niemand zuständig ist — der
             *     Zustand einer abgegebenen Aufgabe, die noch niemand übernommen
             *     hat. Sichtbar offen zu sein ist Absicht.
             * @example m-ben
             */
            zustaendig: string;
            /**
             * Format: date
             * @description gesetzt, wenn die Aufgabe eine echte Frist hat
             */
            frist?: string | null;
            begruendung: components["schemas"]["Begruendung"];
        };
        /**
         * @description Maschinenlesbar. Das Sprachmodell formuliert daraus später einen Satz
         *     für die Oberfläche — es erfindet keine Begründung, es übersetzt eine.
         */
        Begruendung: {
            /** @enum {string} */
            code: "rotation" | "ausgleich" | "feste_person" | "einzige_moeglichkeit" | "frist" | "eigene_aufgabe" | "von_hand" | "absprache";
            /** @description bei `rotation` die Person, die die Aufgabe zuletzt hatte */
            zuletzt_bei?: string | null;
        };
        Bilanz: {
            mitglied_id: string;
            minuten: number;
            kopflast: number;
            /** @description Minuten + Kopflast × 15 */
            gewichtet: number;
            /** @description verfügbare Minuten der ganzen Woche */
            kapazitaet_minuten: number;
            /**
             * @description Verplante Minuten im Verhältnis zur verfügbaren Zeit. Gerechnet
             *     wird mit den reinen Minuten — Kopflast kostet Aufmerksamkeit,
             *     aber keine Uhrzeit (ADR-0004).
             */
            auslastung_prozent: number;
            aufgaben: number;
        };
        Uebersprungen: {
            vorlage_id: string;
            titel: string;
            /** @enum {string} */
            grund: "gilt_nicht" | "abgewaehlt" | "nicht_faellig" | "startdichte" | "keine_kapazitaet" | "niemand_geeignet" | "unbekannt" | "braucht_termin" | "braucht_absprache";
        };
        Rueckmeldung: {
            id: string;
            /**
             * @description Drei und nicht zwei: „Fehler" und „Idee" sind die üblichen, und
             *     dazwischen fällt das Wichtigste durch. `stoert` ist kein Fehler —
             *     die App tut, was sie soll — und keine Idee, weil niemand eine
             *     Lösung anzubieten hat. Genau diese Sätze führen dazu, dass jemand
             *     eine App am Mittwoch zuklappt.
             * @enum {string}
             */
            art: "fehler" | "idee" | "stoert";
            text: string;
            /** @description Seite, Woche und Fassung — von der Oberfläche gesammelt. */
            kontext?: string;
            /**
             * @description Name der meldenden Person. Fehlt, wenn sie den Haushalt verlassen
             *     hat: Die Rückmeldung bleibt wahr, auch wenn niemand mehr
             *     danebensteht.
             */
            wer?: string;
            /** Format: date-time */
            gemeldet_am: string;
        };
        /** @enum {string} */
        Kategorie: "kueche" | "waesche" | "reinigung" | "kind" | "vorrat" | "termine" | "verwaltung" | "wartung" | "sozial" | "aussen";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description die Commit-Kennung des laufenden Dienstes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    getIch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description die Identität des Aufrufers, soweit belegt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ich"];
                };
            };
        };
    };
    listHaushalte: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description alle sichtbaren Haushalte */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Haushalt"][];
                };
            };
        };
    };
    createHaushalt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NeuerHaushalt"];
            };
        };
        responses: {
            /** @description der angelegte Haushalt */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Haushalt"];
                };
            };
            /** @description die Eingabe ergibt keinen Haushalt */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description dafür muss man angemeldet sein */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    updateMitglied: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
                mitgliedId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MitgliedAenderung"];
            };
        };
        responses: {
            /** @description der Haushalt, wie er jetzt aussieht */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Haushalt"];
                };
            };
            /** @description die Änderung ergibt keine Person */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description das dürfen die planenden Personen */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    wocheNeuRechnen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
                /** @example 2026-W38 */
                woche: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description die neu gerechnete Woche */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wochenplan"];
                };
            };
            /** @description das ist keine Kalenderwoche */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description das dürfen die planenden Personen */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    getWochenplan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kennung des Haushalts, z. B. `familie-a` */
                haushaltId: string;
                /** @description ISO-Kalenderwoche, Montag als erster Tag */
                woche: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description der berechnete Plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wochenplan"];
                };
            };
            /** @description die Woche ist nicht lesbar */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    updateHaushalt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HaushaltAenderung"];
            };
        };
        responses: {
            /** @description der Haushalt, wie er jetzt aussieht */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Haushalt"];
                };
            };
            /** @description die Änderung ergibt keinen Haushalt */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description das dürfen die planenden Personen */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    listVorlagen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description die Bibliothek, auf diesen Haushalt bezogen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VorlagenStand"][];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    createEigeneVorlage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NeueVorlage"];
            };
        };
        responses: {
            /** @description die angelegte Aufgabe */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VorlagenStand"];
                };
            };
            /** @description das ergibt keine Aufgabe */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description das dürfen die planenden Personen */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    setVorlage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
                vorlageId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    aktiv: boolean;
                };
            };
        };
        responses: {
            /** @description eingetragen */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description das dürfen die planenden Personen */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    setAbsprache: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
                vorlageId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Sieben Kennungen von Mitgliedern, Index 0 = Montag. Leerer
                     *     Text heißt: für diesen Tag ist nichts abgesprochen.
                     */
                    wochentage: string[];
                };
            };
        };
        responses: {
            /** @description gesetzt */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description so geht das nicht */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description das dürfen die planenden Personen */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description den Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    absprachAbHeute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
                vorlageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description eingetragen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Wie viele Termine entstanden sind. Null ist eine gültige
                         *     Antwort: An den verbleibenden Tagen steht schon etwas,
                         *     oder das Raster trifft in dieser Woche keinen fälligen
                         *     Tag mehr. Die Zahl geht mit hinaus, damit die Oberfläche
                         *     genau das sagen kann, statt „fertig" zu melden und
                         *     nichts zu zeigen.
                         */
                        eingetragen: number;
                    };
                };
            };
            /** @description das dürfen die planenden Personen */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description den Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    setWochentage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
                vorlageId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Index 0 = Montag. Alle sieben falsch heißt: zurück zum
                     *     Rhythmus der Bibliothek.
                     */
                    wochentage: boolean[];
                };
            };
        };
        responses: {
            /** @description gesetzt */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description diese Aufgabe hat keinen Wochenrhythmus */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description das dürfen die planenden Personen */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description den Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    listRueckmeldungen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description die letzten fünfzig */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rueckmeldung"][];
                };
            };
            /** @description das dürfen die planenden Personen */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description den Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    melden: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    art: "fehler" | "idee" | "stoert";
                    text: string;
                    kontext?: string;
                };
            };
        };
        responses: {
            /** @description angekommen */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description so geht das nicht */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description dafür musst du zum Haushalt gehören */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description den Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    listAnlaesse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description alle Anlässe des Haushalts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Anlass"][];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    createAnlass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NeuerAnlass"];
            };
        };
        responses: {
            /** @description der eingetragene Anlass */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Anlass"];
                };
            };
            /** @description das ergibt keinen Anlass */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description das dürfen die planenden Personen */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    deleteAnlass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
                anlassId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description gelöscht */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description das dürfen die planenden Personen */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    setFakten: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: boolean;
                };
            };
        };
        responses: {
            /** @description der Haushalt, wie er jetzt aussieht */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Haushalt"];
                };
            };
            /** @description das ergibt keine Antwort */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description das dürfen die planenden Personen */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    createEinladung: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                haushaltId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Nötig, wenn jemand dazukommt, den es im Haushalt noch nicht
                     *     gibt. Zusammen mit `mitglied` wird sie ignoriert: Diese
                     *     Person hat ihre Rolle bereits, und der Plan rechnet damit.
                     * @enum {string}
                     */
                    rolle?: "planend" | "ausfuehrend";
                    /**
                     * @description Kennung einer Person, die schon im Plan steht, aber noch
                     *     kein Konto hat. Der Code macht den Eingeladenen dann zu
                     *     genau dieser Person — mit ihren Aufgaben, ihrem Verlauf und
                     *     ihrer Kapazität, statt eine zweite gleichen Namens
                     *     anzulegen.
                     */
                    mitglied?: string;
                };
            };
        };
        responses: {
            /** @description der Code */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Einladung"];
                };
            };
            /** @description nur planende Personen dürfen einladen */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    setErledigt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aufgabeId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Fehlt das Feld, gilt „erledigt". */
                    erledigt?: boolean;
                };
            };
        };
        responses: {
            /** @description eingetragen */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description das ist nicht deine Aufgabe */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diese Aufgabe gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    aufgabeAbgeben: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aufgabeId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description Freiwillig. Landet im Protokoll und ist später die
                     *     ehrlichste Rückmeldung, die das Produkt bekommt: Wer
                     *     dieselbe Aufgabe dreimal mit derselben Begründung abgibt,
                     *     hat sie nie gewollt.
                     */
                    grund?: string;
                };
            };
        };
        responses: {
            /** @description abgegeben */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Abgabe"];
                };
            };
            /** @description das ist nicht deine Aufgabe */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diese Aufgabe gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    aufgabeStreichen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aufgabeId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description Fehlt das Feld, gilt „gestrichen". `false` plant die
                     *     Aufgabe wieder ein.
                     */
                    gestrichen?: boolean;
                };
            };
        };
        responses: {
            /** @description eingetragen */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description das ist nicht deine Aufgabe */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diese Aufgabe gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    aufgabeZuteilen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aufgabeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Kennung der Person, die die Aufgabe übernimmt. */
                    mitglied: string;
                };
            };
        };
        responses: {
            /** @description umverteilt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zuteilung"];
                };
            };
            /** @description diese Person kann die Aufgabe nicht übernehmen */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description das ist nicht deine Aufgabe */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diese Aufgabe gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
    acceptEinladung: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description der Haushalt, zu dem die Person jetzt gehört */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Haushalt"];
                };
            };
            /** @description dafür muss man angemeldet sein */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description den Code gibt es nicht, er ist abgelaufen oder verbraucht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
}
