/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Welcher Stand läuft gerade */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verfügbare Haushalte
         * @description Bis zum Datenmodell (T5) sind das die Beispielhaushalte aus dem Repo.
         *     Die Form der Antwort ändert sich dadurch nicht.
         */
        get: operations["listHaushalte"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/haushalte/{haushaltId}/plan/{woche}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wochenplan eines Haushalts */
        get: operations["getWochenplan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Version: {
            /**
             * @description kurze Commit-Kennung oder "dev"
             * @example f18a432
             */
            version: string;
        };
        Fehler: {
            /**
             * @description für Menschen lesbar, deutsch
             * @example die Woche "2026-W99" liegt außerhalb von 1..53
             */
            fehler: string;
        };
        Haushalt: {
            /** @example familie-a */
            id: string;
            /** @example Familie A */
            name: string;
            mitglieder: components["schemas"]["Mitglied"][];
        };
        Mitglied: {
            /** @example m-anna */
            id: string;
            /** @example Anna */
            name: string;
            /**
             * @description `planend` plant und führt aus, `ausfuehrend` führt nur aus,
             *     `betreut` erzeugt Arbeit ohne welche zu übernehmen.
             * @enum {string}
             */
            rolle: "planend" | "ausfuehrend" | "betreut";
        };
        Wochenplan: {
            /** @example 2026-W38 */
            woche: string;
            haushalt: components["schemas"]["Haushalt"];
            aufgaben: components["schemas"]["Aufgabe"][];
            /** @description eine Zeile je Person, die Aufgaben übernehmen kann */
            bilanz: components["schemas"]["Bilanz"][];
            /**
             * @description Was nicht im Plan steht, mit Grund. Ohne dieses Feld könnte die
             *     App nicht erklären, warum etwas fehlt.
             */
            uebersprungen: components["schemas"]["Uebersprungen"][];
        };
        Aufgabe: {
            /** @example t-bad */
            vorlage_id: string;
            /** @example Bad putzen */
            titel: string;
            kategorie: components["schemas"]["Kategorie"];
            /** @enum {string} */
            art: "ausfuehrung" | "organisation";
            /**
             * Format: date
             * @description Kalendertag ohne Uhrzeit und ohne Zeitzone (ADR-0002). Über die
             *     Grenze geht die ISO-Zeichenkette; die Anzeige rechnet sie in
             *     Europe/Berlin um.
             * @example 2026-09-19
             */
            tag: string;
            /** @enum {string} */
            zeitfenster: "egal" | "morgens" | "abends";
            /** @example 35 */
            dauer_min: number;
            /** @description Planungs- und Erinnerungsaufwand, unabhängig von der Dauer */
            kopflast: number;
            /**
             * @description Kennung des Mitglieds
             * @example m-ben
             */
            zustaendig: string;
            /**
             * Format: date
             * @description gesetzt, wenn die Aufgabe eine echte Frist hat
             */
            frist?: string | null;
            begruendung: components["schemas"]["Begruendung"];
        };
        /**
         * @description Maschinenlesbar. Das Sprachmodell formuliert daraus später einen Satz
         *     für die Oberfläche — es erfindet keine Begründung, es übersetzt eine.
         */
        Begruendung: {
            /** @enum {string} */
            code: "rotation" | "ausgleich" | "feste_person" | "einzige_moeglichkeit" | "frist" | "eigene_aufgabe";
            /** @description bei `rotation` die Person, die die Aufgabe zuletzt hatte */
            zuletzt_bei?: string | null;
        };
        Bilanz: {
            mitglied_id: string;
            minuten: number;
            kopflast: number;
            /** @description Minuten + Kopflast × 15 */
            gewichtet: number;
            /** @description verfügbare Minuten der ganzen Woche */
            kapazitaet_minuten: number;
            /**
             * @description Verplante Minuten im Verhältnis zur verfügbaren Zeit. Gerechnet
             *     wird mit den reinen Minuten — Kopflast kostet Aufmerksamkeit,
             *     aber keine Uhrzeit (ADR-0004).
             */
            auslastung_prozent: number;
            aufgaben: number;
        };
        Uebersprungen: {
            vorlage_id: string;
            titel: string;
            /** @enum {string} */
            grund: "gilt_nicht" | "abgewaehlt" | "nicht_faellig" | "startdichte" | "keine_kapazitaet" | "niemand_geeignet";
        };
        /** @enum {string} */
        Kategorie: "kueche" | "waesche" | "reinigung" | "kind" | "vorrat" | "termine" | "verwaltung" | "wartung" | "sozial" | "aussen";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description die Commit-Kennung des laufenden Dienstes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    listHaushalte: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description alle sichtbaren Haushalte */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Haushalt"][];
                };
            };
        };
    };
    getWochenplan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kennung des Haushalts, z. B. `familie-a` */
                haushaltId: string;
                /** @description ISO-Kalenderwoche, Montag als erster Tag */
                woche: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description der berechnete Plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wochenplan"];
                };
            };
            /** @description die Woche ist nicht lesbar */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
            /** @description diesen Haushalt gibt es nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fehler"];
                };
            };
        };
    };
}
