// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anlass.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOccasion = `-- name: CreateOccasion :one
INSERT INTO occasion (household_id, title, day, kind, yearly)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, household_id, title, day, kind, yearly, created_at
`

type CreateOccasionParams struct {
	HouseholdID pgtype.UUID
	Title       string
	Day         pgtype.Date
	Kind        string
	Yearly      bool
}

func (q *Queries) CreateOccasion(ctx context.Context, arg CreateOccasionParams) (Occasion, error) {
	row := q.db.QueryRow(ctx, createOccasion,
		arg.HouseholdID,
		arg.Title,
		arg.Day,
		arg.Kind,
		arg.Yearly,
	)
	var i Occasion
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Title,
		&i.Day,
		&i.Kind,
		&i.Yearly,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOccasion = `-- name: DeleteOccasion :exec
DELETE FROM occasion WHERE id = $1 AND household_id = $2
`

type DeleteOccasionParams struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
}

// Mit Haushalt gefragt, nicht nur mit der Kennung: Eine Kennung allein wäre
// eine Berechtigungsprüfung, die an einem vergessenen if hängt.
func (q *Queries) DeleteOccasion(ctx context.Context, arg DeleteOccasionParams) error {
	_, err := q.db.Exec(ctx, deleteOccasion, arg.ID, arg.HouseholdID)
	return err
}

const listOccasions = `-- name: ListOccasions :many
SELECT id, household_id, title, day, kind, yearly, created_at FROM occasion WHERE household_id = $1 ORDER BY day, title
`

func (q *Queries) ListOccasions(ctx context.Context, householdID pgtype.UUID) ([]Occasion, error) {
	rows, err := q.db.Query(ctx, listOccasions, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Occasion{}
	for rows.Next() {
		var i Occasion
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Title,
			&i.Day,
			&i.Kind,
			&i.Yearly,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
