// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO event (household_id, member_id, task_instance_id, kind, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, household_id, member_id, task_instance_id, kind, payload, occurred_at
`

type AppendEventParams struct {
	HouseholdID    pgtype.UUID
	MemberID       pgtype.UUID
	TaskInstanceID pgtype.UUID
	Kind           string
	Payload        []byte
}

// Die einzige schreibende Operation auf dem Protokoll. Ändern und Löschen
// verhindert der Trigger in der Migration, nicht die Disziplin des Aufrufers.
func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, appendEvent,
		arg.HouseholdID,
		arg.MemberID,
		arg.TaskInstanceID,
		arg.Kind,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.TaskInstanceID,
		&i.Kind,
		&i.Payload,
		&i.OccurredAt,
	)
	return i, err
}

const appendHistoricEvent = `-- name: AppendHistoricEvent :one
INSERT INTO event (household_id, member_id, task_instance_id, kind, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, household_id, member_id, task_instance_id, kind, payload, occurred_at
`

type AppendHistoricEventParams struct {
	HouseholdID    pgtype.UUID
	MemberID       pgtype.UUID
	TaskInstanceID pgtype.UUID
	Kind           string
	Payload        []byte
	OccurredAt     pgtype.Timestamptz
}

// Nur für den Import: ein Ereignis mit einem Zeitpunkt aus der Vergangenheit.
//
// Im Betrieb setzt die Datenbank now(), und das ist keine Bequemlichkeit: Ein
// Aufrufer, der den Zeitpunkt bestimmen darf, kann die Vergangenheit
// umschreiben — und dagegen steht das ganze Protokoll. Der Import ist die eine
// Ausnahme, und sie hat deshalb ihre eigene Abfrage statt eines Parameters an
// der normalen.
func (q *Queries) AppendHistoricEvent(ctx context.Context, arg AppendHistoricEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, appendHistoricEvent,
		arg.HouseholdID,
		arg.MemberID,
		arg.TaskInstanceID,
		arg.Kind,
		arg.Payload,
		arg.OccurredAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MemberID,
		&i.TaskInstanceID,
		&i.Kind,
		&i.Payload,
		&i.OccurredAt,
	)
	return i, err
}

const countEvents = `-- name: CountEvents :one
SELECT count(*) FROM event WHERE household_id = $1
`

// Der Import legt Historie nur an, wenn noch keine da ist.
//
// Das Protokoll ist reines Anhängen — es lässt sich nicht bereinigen, auch
// nicht vom Import. Also darf er nur einmal schreiben, sonst wächst bei jedem
// Lauf ein weiterer Satz „erledigt" hinzu.
func (q *Queries) CountEvents(ctx context.Context, householdID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const lastAssigneePerTemplate = `-- name: LastAssigneePerTemplate :many
SELECT DISTINCT ON (t.template_id)
    t.template_id,
    a.member_id
FROM task_instance t
JOIN assignment a ON a.task_instance_id = t.id
WHERE t.household_id = $1
ORDER BY t.template_id, t.day DESC
`

type LastAssigneePerTemplateRow struct {
	TemplateID string
	MemberID   pgtype.UUID
}

// Wer eine Vorlage zuletzt hatte — die Grundlage der Rotation.
//
// DISTINCT ON ist Postgres-eigen und hier genau richtig: erste Zeile je
// Vorlage, sortiert nach Tag absteigend. In Standard-SQL bräuchte es dafür
// eine Fensterfunktion und eine Unterabfrage.
func (q *Queries) LastAssigneePerTemplate(ctx context.Context, householdID pgtype.UUID) ([]LastAssigneePerTemplateRow, error) {
	rows, err := q.db.Query(ctx, lastAssigneePerTemplate, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LastAssigneePerTemplateRow{}
	for rows.Next() {
		var i LastAssigneePerTemplateRow
		if err := rows.Scan(&i.TemplateID, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastDonePerTemplate = `-- name: LastDonePerTemplate :many
SELECT
    t.template_id,
    max((e.occurred_at AT TIME ZONE h.timezone))::date AS last_done
FROM event e
JOIN task_instance t ON t.id = e.task_instance_id
JOIN household h ON h.id = e.household_id
WHERE e.household_id = $1 AND e.kind = 'erledigt'
GROUP BY t.template_id
`

type LastDonePerTemplateRow struct {
	TemplateID string
	LastDone   pgtype.Date
}

// Verdichtet das Protokoll zu dem, was der Planer als Historie braucht.
//
// AT TIME ZONE h.timezone vor dem Schnitt auf das Datum: Der Zeitstempel liegt
// in UTC, die Frage „an welchem Tag war das?" ist aber eine Frage nach der
// Ortszeit des Haushalts (ADR-0002). Ohne die Umrechnung landet eine Aufgabe,
// die sonntags um 23:30 abgehakt wurde, im Montag.
func (q *Queries) LastDonePerTemplate(ctx context.Context, householdID pgtype.UUID) ([]LastDonePerTemplateRow, error) {
	rows, err := q.db.Query(ctx, lastDonePerTemplate, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LastDonePerTemplateRow{}
	for rows.Next() {
		var i LastDonePerTemplateRow
		if err := rows.Scan(&i.TemplateID, &i.LastDone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, household_id, member_id, task_instance_id, kind, payload, occurred_at FROM event
WHERE household_id = $1
ORDER BY occurred_at DESC, id DESC
LIMIT $2
`

type ListEventsParams struct {
	HouseholdID pgtype.UUID
	Limit       int32
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.HouseholdID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.MemberID,
			&i.TaskInstanceID,
			&i.Kind,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
