// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: household.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO household (name, home, has_car, has_yard, pets, timezone)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, home, has_car, has_yard, pets, timezone, created_at
`

type CreateHouseholdParams struct {
	Name     string
	Home     string
	HasCar   bool
	HasYard  bool
	Pets     []string
	Timezone string
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold,
		arg.Name,
		arg.Home,
		arg.HasCar,
		arg.HasYard,
		arg.Pets,
		arg.Timezone,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Home,
		&i.HasCar,
		&i.HasYard,
		&i.Pets,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getHousehold = `-- name: GetHousehold :one
SELECT id, name, home, has_car, has_yard, pets, timezone, created_at FROM household WHERE id = $1
`

func (q *Queries) GetHousehold(ctx context.Context, id pgtype.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHousehold, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Home,
		&i.HasCar,
		&i.HasYard,
		&i.Pets,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const listHouseholdsForAuthUser = `-- name: ListHouseholdsForAuthUser :many
SELECT h.id, h.name, h.home, h.has_car, h.has_yard, h.pets, h.timezone, h.created_at
FROM household h
JOIN member m ON m.household_id = h.id
WHERE m.auth_user_id = $1
ORDER BY h.created_at
`

// Alle Haushalte, in denen diese angemeldete Person Mitglied ist.
// Der Weg führt immer über member: Es gibt keine Beziehung zwischen einem
// Login und einem Haushalt, die nicht über eine Person läuft.
func (q *Queries) ListHouseholdsForAuthUser(ctx context.Context, authUserID *string) ([]Household, error) {
	rows, err := q.db.Query(ctx, listHouseholdsForAuthUser, authUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Household{}
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Home,
			&i.HasCar,
			&i.HasYard,
			&i.Pets,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
