// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: household.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAgreementRow = `-- name: ClearAgreementRow :exec
DELETE FROM agreement WHERE household_id = $1 AND template_id = $2
`

type ClearAgreementRowParams struct {
	HouseholdID pgtype.UUID
	TemplateID  string
}

// Das ganze Raster einer Vorlage leeren — der erste Schritt beim Setzen einer
// kompletten Zeile. Sieben Plätze einzeln abzugleichen wäre sieben Abfragen
// und dieselbe Wirkung.
func (q *Queries) ClearAgreementRow(ctx context.Context, arg ClearAgreementRowParams) error {
	_, err := q.db.Exec(ctx, clearAgreementRow, arg.HouseholdID, arg.TemplateID)
	return err
}

const clearTemplateWeekdays = `-- name: ClearTemplateWeekdays :exec
DELETE FROM template_weekday WHERE household_id = $1 AND template_id = $2
`

type ClearTemplateWeekdaysParams struct {
	HouseholdID pgtype.UUID
	TemplateID  string
}

// Alle Wochentage einer Vorlage löschen — der erste Schritt beim Setzen einer
// neuen Auswahl und zugleich das Zurücksetzen auf den Rhythmus der Bibliothek.
func (q *Queries) ClearTemplateWeekdays(ctx context.Context, arg ClearTemplateWeekdaysParams) error {
	_, err := q.db.Exec(ctx, clearTemplateWeekdays, arg.HouseholdID, arg.TemplateID)
	return err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO household (name, home, has_car, has_yard, pets, timezone, facts, rooms, baths)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, home, has_car, has_yard, pets, timezone, created_at, slug, facts, rooms, baths
`

type CreateHouseholdParams struct {
	Name     string
	Home     string
	HasCar   bool
	HasYard  bool
	Pets     []string
	Timezone string
	Facts    []byte
	Rooms    int32
	Baths    int32
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold,
		arg.Name,
		arg.Home,
		arg.HasCar,
		arg.HasYard,
		arg.Pets,
		arg.Timezone,
		arg.Facts,
		arg.Rooms,
		arg.Baths,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Home,
		&i.HasCar,
		&i.HasYard,
		&i.Pets,
		&i.Timezone,
		&i.CreatedAt,
		&i.Slug,
		&i.Facts,
		&i.Rooms,
		&i.Baths,
	)
	return i, err
}

const getHousehold = `-- name: GetHousehold :one
SELECT id, name, home, has_car, has_yard, pets, timezone, created_at, slug, facts, rooms, baths FROM household WHERE id = $1
`

func (q *Queries) GetHousehold(ctx context.Context, id pgtype.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHousehold, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Home,
		&i.HasCar,
		&i.HasYard,
		&i.Pets,
		&i.Timezone,
		&i.CreatedAt,
		&i.Slug,
		&i.Facts,
		&i.Rooms,
		&i.Baths,
	)
	return i, err
}

const getHouseholdBySlug = `-- name: GetHouseholdBySlug :one
SELECT id, name, home, has_car, has_yard, pets, timezone, created_at, slug, facts, rooms, baths FROM household WHERE slug = $1
`

func (q *Queries) GetHouseholdBySlug(ctx context.Context, slug *string) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdBySlug, slug)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Home,
		&i.HasCar,
		&i.HasYard,
		&i.Pets,
		&i.Timezone,
		&i.CreatedAt,
		&i.Slug,
		&i.Facts,
		&i.Rooms,
		&i.Baths,
	)
	return i, err
}

const listAgreements = `-- name: ListAgreements :many
SELECT template_id, weekday, member_id
FROM agreement
WHERE household_id = $1
ORDER BY template_id, weekday
`

type ListAgreementsRow struct {
	TemplateID string
	Weekday    int32
	MemberID   pgtype.UUID
}

// Das Wochenraster des Haushalts: je Vorlage und Wochentag eine Person.
func (q *Queries) ListAgreements(ctx context.Context, householdID pgtype.UUID) ([]ListAgreementsRow, error) {
	rows, err := q.db.Query(ctx, listAgreements, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgreementsRow{}
	for rows.Next() {
		var i ListAgreementsRow
		if err := rows.Scan(&i.TemplateID, &i.Weekday, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDemoHouseholds = `-- name: ListDemoHouseholds :many
SELECT id, name, home, has_car, has_yard, pets, timezone, created_at, slug, facts, rooms, baths FROM household WHERE slug IS NOT NULL ORDER BY created_at
`

// Haushalte mit Slug sind die aus dem Repo: öffentlich sichtbar, ohne
// Anmeldung. Alles ohne Slug gehört jemandem.
func (q *Queries) ListDemoHouseholds(ctx context.Context) ([]Household, error) {
	rows, err := q.db.Query(ctx, listDemoHouseholds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Household{}
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Home,
			&i.HasCar,
			&i.HasYard,
			&i.Pets,
			&i.Timezone,
			&i.CreatedAt,
			&i.Slug,
			&i.Facts,
			&i.Rooms,
			&i.Baths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholds = `-- name: ListHouseholds :many
SELECT id, name, home, has_car, has_yard, pets, timezone, created_at, slug, facts, rooms, baths FROM household ORDER BY created_at
`

// Alle Haushalte. Ab der Anmeldung tritt ListHouseholdsForAuthUser an diese
// Stelle — bis dahin sind es die Beispielhaushalte aus dem Repo.
func (q *Queries) ListHouseholds(ctx context.Context) ([]Household, error) {
	rows, err := q.db.Query(ctx, listHouseholds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Household{}
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Home,
			&i.HasCar,
			&i.HasYard,
			&i.Pets,
			&i.Timezone,
			&i.CreatedAt,
			&i.Slug,
			&i.Facts,
			&i.Rooms,
			&i.Baths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdsForAuthUser = `-- name: ListHouseholdsForAuthUser :many
SELECT h.id, h.name, h.home, h.has_car, h.has_yard, h.pets, h.timezone, h.created_at, h.slug, h.facts, h.rooms, h.baths
FROM household h
JOIN member m ON m.household_id = h.id
WHERE m.auth_user_id = $1
ORDER BY h.created_at
`

// Alle Haushalte, in denen diese angemeldete Person Mitglied ist.
// Der Weg führt immer über member: Es gibt keine Beziehung zwischen einem
// Login und einem Haushalt, die nicht über eine Person läuft.
func (q *Queries) ListHouseholdsForAuthUser(ctx context.Context, authUserID *string) ([]Household, error) {
	rows, err := q.db.Query(ctx, listHouseholdsForAuthUser, authUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Household{}
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Home,
			&i.HasCar,
			&i.HasYard,
			&i.Pets,
			&i.Timezone,
			&i.CreatedAt,
			&i.Slug,
			&i.Facts,
			&i.Rooms,
			&i.Baths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateWeekdays = `-- name: ListTemplateWeekdays :many
SELECT template_id, weekday
FROM template_weekday
WHERE household_id = $1
ORDER BY template_id, weekday
`

type ListTemplateWeekdaysRow struct {
	TemplateID string
	Weekday    int32
}

// Die Wochentage, die dieser Haushalt für Vorlagen festgelegt hat.
func (q *Queries) ListTemplateWeekdays(ctx context.Context, householdID pgtype.UUID) ([]ListTemplateWeekdaysRow, error) {
	rows, err := q.db.Query(ctx, listTemplateWeekdays, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplateWeekdaysRow{}
	for rows.Next() {
		var i ListTemplateWeekdaysRow
		if err := rows.Scan(&i.TemplateID, &i.Weekday); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgreement = `-- name: SetAgreement :exec
INSERT INTO agreement (household_id, template_id, weekday, member_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (household_id, template_id, weekday)
DO UPDATE SET member_id = EXCLUDED.member_id
`

type SetAgreementParams struct {
	HouseholdID pgtype.UUID
	TemplateID  string
	Weekday     int32
	MemberID    pgtype.UUID
}

// Einen Platz im Raster besetzen. Zweimal dasselbe zu setzen ist kein Fehler.
func (q *Queries) SetAgreement(ctx context.Context, arg SetAgreementParams) error {
	_, err := q.db.Exec(ctx, setAgreement,
		arg.HouseholdID,
		arg.TemplateID,
		arg.Weekday,
		arg.MemberID,
	)
	return err
}

const setFacts = `-- name: SetFacts :one
UPDATE household
SET facts = facts || $2::jsonb
WHERE id = $1
RETURNING id, name, home, has_car, has_yard, pets, timezone, created_at, slug, facts, rooms, baths
`

type SetFactsParams struct {
	ID      pgtype.UUID
	Column2 []byte
}

// Fakten zusammenführen, nicht ersetzen: || vereinigt zwei JSONB-Objekte,
// rechts gewinnt. Ein Formular, das nur eine Antwort schickt, soll die
// übrigen nicht löschen.
func (q *Queries) SetFacts(ctx context.Context, arg SetFactsParams) (Household, error) {
	row := q.db.QueryRow(ctx, setFacts, arg.ID, arg.Column2)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Home,
		&i.HasCar,
		&i.HasYard,
		&i.Pets,
		&i.Timezone,
		&i.CreatedAt,
		&i.Slug,
		&i.Facts,
		&i.Rooms,
		&i.Baths,
	)
	return i, err
}

const setTemplateWeekday = `-- name: SetTemplateWeekday :exec
INSERT INTO template_weekday (household_id, template_id, weekday)
VALUES ($1, $2, $3)
ON CONFLICT (household_id, template_id, weekday) DO NOTHING
`

type SetTemplateWeekdayParams struct {
	HouseholdID pgtype.UUID
	TemplateID  string
	Weekday     int32
}

// Einen Wochentag festlegen. Zweimal denselben zu setzen ist kein Fehler.
func (q *Queries) SetTemplateWeekday(ctx context.Context, arg SetTemplateWeekdayParams) error {
	_, err := q.db.Exec(ctx, setTemplateWeekday, arg.HouseholdID, arg.TemplateID, arg.Weekday)
	return err
}

const updateHousehold = `-- name: UpdateHousehold :one
UPDATE household SET
    name     = COALESCE($1, name),
    home     = COALESCE($2, home),
    has_car  = COALESCE($3, has_car),
    has_yard = COALESCE($4, has_yard),
    pets     = COALESCE($5, pets),
    timezone = COALESCE($6, timezone),
    rooms    = COALESCE($7, rooms),
    baths    = COALESCE($8, baths)
WHERE id = $9
RETURNING id, name, home, has_car, has_yard, pets, timezone, created_at, slug, facts, rooms, baths
`

type UpdateHouseholdParams struct {
	Name     *string
	Home     *string
	HasCar   *bool
	HasYard  *bool
	Pets     []string
	Timezone *string
	Rooms    *int32
	Baths    *int32
	ID       pgtype.UUID
}

// Einstellungen ändern. Jedes Feld darf fehlen; was fehlt, bleibt stehen.
//
// COALESCE statt einer gebauten Anweisung: Der Unterschied zwischen „nicht
// mitgeschickt" und „auf leer gesetzt" wird hier entschieden und nicht in Go
// zusammengestückelt.
func (q *Queries) UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, updateHousehold,
		arg.Name,
		arg.Home,
		arg.HasCar,
		arg.HasYard,
		arg.Pets,
		arg.Timezone,
		arg.Rooms,
		arg.Baths,
		arg.ID,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Home,
		&i.HasCar,
		&i.HasYard,
		&i.Pets,
		&i.Timezone,
		&i.CreatedAt,
		&i.Slug,
		&i.Facts,
		&i.Rooms,
		&i.Baths,
	)
	return i, err
}

const upsertDemoHousehold = `-- name: UpsertDemoHousehold :one
INSERT INTO household (slug, name, home, has_car, has_yard, pets, timezone, facts, rooms, baths)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (slug) DO UPDATE
    SET name     = EXCLUDED.name,
        home     = EXCLUDED.home,
        has_car  = EXCLUDED.has_car,
        has_yard = EXCLUDED.has_yard,
        pets     = EXCLUDED.pets,
        timezone = EXCLUDED.timezone,
        facts    = EXCLUDED.facts,
        rooms    = EXCLUDED.rooms,
        baths    = EXCLUDED.baths
RETURNING id, name, home, has_car, has_yard, pets, timezone, created_at, slug, facts, rooms, baths
`

type UpsertDemoHouseholdParams struct {
	Slug     *string
	Name     string
	Home     string
	HasCar   bool
	HasYard  bool
	Pets     []string
	Timezone string
	Facts    []byte
	Rooms    int32
	Baths    int32
}

// Haushalte aus dem Repo. Der Slug ist der Schlüssel, damit ein zweiter
// Import dieselbe Zeile trifft statt eine neue anzulegen.
func (q *Queries) UpsertDemoHousehold(ctx context.Context, arg UpsertDemoHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, upsertDemoHousehold,
		arg.Slug,
		arg.Name,
		arg.Home,
		arg.HasCar,
		arg.HasYard,
		arg.Pets,
		arg.Timezone,
		arg.Facts,
		arg.Rooms,
		arg.Baths,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Home,
		&i.HasCar,
		&i.HasYard,
		&i.Pets,
		&i.Timezone,
		&i.CreatedAt,
		&i.Slug,
		&i.Facts,
		&i.Rooms,
		&i.Baths,
	)
	return i, err
}
