// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeInvitation = `-- name: ConsumeInvitation :one
UPDATE invitation
SET used_at = now(), used_by = $2
WHERE code = $1 AND used_at IS NULL AND expires_at > now()
RETURNING code, household_id, role, created_by, created_at, expires_at, used_at, used_by
`

type ConsumeInvitationParams struct {
	Code   string
	UsedBy pgtype.UUID
}

// Verbraucht die Einladung — und zwar nur, wenn sie noch zu haben ist.
//
// Die Bedingungen stehen in der UPDATE-Anweisung und nicht davor in Go. Der
// Unterschied ist nicht Stil, sondern Korrektheit: „erst prüfen, dann
// schreiben" lässt zwei gleichzeitige Beitritte beide durch, weil beide
// prüfen, bevor einer schreibt. So gewinnt genau einer, und der andere
// bekommt keine Zeile zurück.
func (q *Queries) ConsumeInvitation(ctx context.Context, arg ConsumeInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, consumeInvitation, arg.Code, arg.UsedBy)
	var i Invitation
	err := row.Scan(
		&i.Code,
		&i.HouseholdID,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitation (code, household_id, role, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING code, household_id, role, created_by, created_at, expires_at, used_at, used_by
`

type CreateInvitationParams struct {
	Code        string
	HouseholdID pgtype.UUID
	Role        string
	CreatedBy   pgtype.UUID
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Code,
		arg.HouseholdID,
		arg.Role,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.Code,
		&i.HouseholdID,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const createMemberWithRole = `-- name: CreateMemberWithRole :one
INSERT INTO member (household_id, name, role, capacity_minutes, auth_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, household_id, name, role, birth_year, care, capacity_minutes, auth_user_id, created_at
`

type CreateMemberWithRoleParams struct {
	HouseholdID     pgtype.UUID
	Name            string
	Role            string
	CapacityMinutes []int32
	AuthUserID      *string
}

// Wie CreateMember, aber für den Beitritt über eine Einladung: Der Haushalt
// steht fest, die Rolle kommt aus der Einladung.
func (q *Queries) CreateMemberWithRole(ctx context.Context, arg CreateMemberWithRoleParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMemberWithRole,
		arg.HouseholdID,
		arg.Name,
		arg.Role,
		arg.CapacityMinutes,
		arg.AuthUserID,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Role,
		&i.BirthYear,
		&i.Care,
		&i.CapacityMinutes,
		&i.AuthUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitation = `-- name: GetInvitation :one
SELECT code, household_id, role, created_by, created_at, expires_at, used_at, used_by FROM invitation WHERE code = $1
`

// Der Code allein genügt; ob er noch gilt, entscheidet der Aufrufer anhand
// von expires_at und used_at. Absichtlich nicht in der Abfrage gefiltert:
// „abgelaufen" und „schon benutzt" sind verschiedene Auskünfte, und wer sie
// hier wegfiltert, kann sie später nicht mehr geben.
func (q *Queries) GetInvitation(ctx context.Context, code string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitation, code)
	var i Invitation
	err := row.Scan(
		&i.Code,
		&i.HouseholdID,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const listOpenInvitations = `-- name: ListOpenInvitations :many
SELECT code, household_id, role, created_by, created_at, expires_at, used_at, used_by FROM invitation
WHERE household_id = $1 AND used_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListOpenInvitations(ctx context.Context, householdID pgtype.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listOpenInvitations, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.Code,
			&i.HouseholdID,
			&i.Role,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleInHousehold = `-- name: RoleInHousehold :one
SELECT role FROM member WHERE household_id = $1 AND auth_user_id = $2
`

type RoleInHouseholdParams struct {
	HouseholdID pgtype.UUID
	AuthUserID  *string
}

// Die Rolle des Aufrufers in diesem Haushalt. Keine Zeile heißt: kein
// Mitglied.
func (q *Queries) RoleInHousehold(ctx context.Context, arg RoleInHouseholdParams) (string, error) {
	row := q.db.QueryRow(ctx, roleInHousehold, arg.HouseholdID, arg.AuthUserID)
	var role string
	err := row.Scan(&role)
	return role, err
}
