// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO member (household_id, name, role, birth_year, care, capacity_minutes, auth_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, household_id, name, role, birth_year, care, capacity_minutes, auth_user_id, created_at
`

type CreateMemberParams struct {
	HouseholdID     pgtype.UUID
	Name            string
	Role            string
	BirthYear       *int32
	Care            *string
	CapacityMinutes []int32
	AuthUserID      *string
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.HouseholdID,
		arg.Name,
		arg.Role,
		arg.BirthYear,
		arg.Care,
		arg.CapacityMinutes,
		arg.AuthUserID,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Role,
		&i.BirthYear,
		&i.Care,
		&i.CapacityMinutes,
		&i.AuthUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberByAuthUserID = `-- name: GetMemberByAuthUserID :one
SELECT id, household_id, name, role, birth_year, care, capacity_minutes, auth_user_id, created_at FROM member WHERE auth_user_id = $1
`

// Der Übergang von der Anmeldung in die Fachwelt: Better Auth kennt nur eine
// Nutzerkennung, alles Weitere hängt an dieser einen Zeile.
func (q *Queries) GetMemberByAuthUserID(ctx context.Context, authUserID *string) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByAuthUserID, authUserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Role,
		&i.BirthYear,
		&i.Care,
		&i.CapacityMinutes,
		&i.AuthUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, household_id, name, role, birth_year, care, capacity_minutes, auth_user_id, created_at FROM member WHERE household_id = $1 ORDER BY created_at
`

func (q *Queries) ListMembers(ctx context.Context, householdID pgtype.UUID) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Role,
			&i.BirthYear,
			&i.Care,
			&i.CapacityMinutes,
			&i.AuthUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMemberAuthUser = `-- name: SetMemberAuthUser :one
UPDATE member SET auth_user_id = $2 WHERE id = $1 RETURNING id, household_id, name, role, birth_year, care, capacity_minutes, auth_user_id, created_at
`

type SetMemberAuthUserParams struct {
	ID         pgtype.UUID
	AuthUserID *string
}

// Verbindet eine bestehende Person mit einem Login — der Fall, dass jemand
// in einen Haushalt eingeladen wird, der ihn schon als Mitglied führt.
func (q *Queries) SetMemberAuthUser(ctx context.Context, arg SetMemberAuthUserParams) (Member, error) {
	row := q.db.QueryRow(ctx, setMemberAuthUser, arg.ID, arg.AuthUserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Role,
		&i.BirthYear,
		&i.Care,
		&i.CapacityMinutes,
		&i.AuthUserID,
		&i.CreatedAt,
	)
	return i, err
}
