// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO member (household_id, name, role, birth_year, care, capacity_minutes, auth_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, household_id, name, role, birth_year, care, capacity_minutes, auth_user_id, created_at
`

type CreateMemberParams struct {
	HouseholdID     pgtype.UUID
	Name            string
	Role            string
	BirthYear       *int32
	Care            *string
	CapacityMinutes []int32
	AuthUserID      *string
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.HouseholdID,
		arg.Name,
		arg.Role,
		arg.BirthYear,
		arg.Care,
		arg.CapacityMinutes,
		arg.AuthUserID,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Role,
		&i.BirthYear,
		&i.Care,
		&i.CapacityMinutes,
		&i.AuthUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberInHousehold = `-- name: GetMemberInHousehold :one
SELECT id, household_id, name, role, birth_year, care, capacity_minutes, auth_user_id, created_at FROM member WHERE household_id = $1 AND auth_user_id = $2
`

type GetMemberInHouseholdParams struct {
	HouseholdID pgtype.UUID
	AuthUserID  *string
}

// Der Übergang von der Anmeldung in die Fachwelt: Better Auth kennt nur eine
// Nutzerkennung, alles Weitere hängt an dieser einen Zeile.
//
// Immer MIT Haushalt gefragt. Dieselbe Anmeldung kann in mehreren Haushalten
// eine Person sein, mit verschiedenen Rollen und verschiedenen Namen — eine
// Abfrage ohne household_id würde irgendeine davon zurückgeben.
func (q *Queries) GetMemberInHousehold(ctx context.Context, arg GetMemberInHouseholdParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberInHousehold, arg.HouseholdID, arg.AuthUserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Role,
		&i.BirthYear,
		&i.Care,
		&i.CapacityMinutes,
		&i.AuthUserID,
		&i.CreatedAt,
	)
	return i, err
}

const hasMembership = `-- name: HasMembership :one
SELECT EXISTS(SELECT 1 FROM member WHERE auth_user_id = $1)
`

// Ist diese angemeldete Person überhaupt irgendwo Mitglied? Die Frage
// entscheidet, ob beim ersten Zugriff ein Haushalt entsteht.
func (q *Queries) HasMembership(ctx context.Context, authUserID *string) (bool, error) {
	row := q.db.QueryRow(ctx, hasMembership, authUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isMemberOf = `-- name: IsMemberOf :one
SELECT EXISTS(
    SELECT 1 FROM member WHERE household_id = $1 AND auth_user_id = $2
)
`

type IsMemberOfParams struct {
	HouseholdID pgtype.UUID
	AuthUserID  *string
}

// Darf diese Person diesen Haushalt sehen?
//
// Eine Abfrage, kein Abgleich in Go: Die Antwort soll aus derselben Quelle
// kommen wie die Daten, sonst driften Berechtigung und Inhalt auseinander.
func (q *Queries) IsMemberOf(ctx context.Context, arg IsMemberOfParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMemberOf, arg.HouseholdID, arg.AuthUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, household_id, name, role, birth_year, care, capacity_minutes, auth_user_id, created_at FROM member WHERE household_id = $1 ORDER BY created_at, name
`

func (q *Queries) ListMembers(ctx context.Context, householdID pgtype.UUID) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Role,
			&i.BirthYear,
			&i.Care,
			&i.CapacityMinutes,
			&i.AuthUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMemberAuthUser = `-- name: SetMemberAuthUser :one
UPDATE member SET auth_user_id = $2 WHERE id = $1 RETURNING id, household_id, name, role, birth_year, care, capacity_minutes, auth_user_id, created_at
`

type SetMemberAuthUserParams struct {
	ID         pgtype.UUID
	AuthUserID *string
}

// Verbindet eine bestehende Person mit einem Login — der Fall, dass jemand
// in einen Haushalt eingeladen wird, der ihn schon als Mitglied führt.
func (q *Queries) SetMemberAuthUser(ctx context.Context, arg SetMemberAuthUserParams) (Member, error) {
	row := q.db.QueryRow(ctx, setMemberAuthUser, arg.ID, arg.AuthUserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Role,
		&i.BirthYear,
		&i.Care,
		&i.CapacityMinutes,
		&i.AuthUserID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertMember = `-- name: UpsertMember :one
INSERT INTO member (household_id, name, role, birth_year, care, capacity_minutes)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (household_id, name) DO UPDATE
    SET role             = EXCLUDED.role,
        birth_year       = EXCLUDED.birth_year,
        care             = EXCLUDED.care,
        capacity_minutes = EXCLUDED.capacity_minutes
RETURNING id, household_id, name, role, birth_year, care, capacity_minutes, auth_user_id, created_at
`

type UpsertMemberParams struct {
	HouseholdID     pgtype.UUID
	Name            string
	Role            string
	BirthYear       *int32
	Care            *string
	CapacityMinutes []int32
}

// Schlüssel ist der Name im Haushalt. auth_user_id bleibt unangetastet: Wer
// sich einmal angemeldet hat, verliert die Verbindung nicht, weil jemand die
// Beispieldaten neu einliest.
func (q *Queries) UpsertMember(ctx context.Context, arg UpsertMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, upsertMember,
		arg.HouseholdID,
		arg.Name,
		arg.Role,
		arg.BirthYear,
		arg.Care,
		arg.CapacityMinutes,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Role,
		&i.BirthYear,
		&i.Care,
		&i.CapacityMinutes,
		&i.AuthUserID,
		&i.CreatedAt,
	)
	return i, err
}
