// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agreement struct {
	HouseholdID pgtype.UUID
	TemplateID  string
	Weekday     int32
	MemberID    pgtype.UUID
}

type Assignment struct {
	ID             pgtype.UUID
	TaskInstanceID pgtype.UUID
	MemberID       pgtype.UUID
	ReasonCode     string
	ReasonPrevious pgtype.UUID
	Manual         bool
	CreatedAt      pgtype.Timestamptz
}

type Event struct {
	ID             int64
	HouseholdID    pgtype.UUID
	MemberID       pgtype.UUID
	TaskInstanceID pgtype.UUID
	Kind           string
	Payload        []byte
	OccurredAt     pgtype.Timestamptz
}

type Feedback struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	MemberID    pgtype.UUID
	Art         string
	Text        string
	Kontext     string
	CreatedAt   pgtype.Timestamptz
}

type Household struct {
	ID        pgtype.UUID
	Name      string
	Home      string
	HasCar    bool
	HasYard   bool
	Pets      []string
	Timezone  string
	CreatedAt pgtype.Timestamptz
	Slug      *string
	Facts     []byte
	Rooms     int32
	Baths     int32
}

type Invitation struct {
	Code        string
	HouseholdID pgtype.UUID
	Role        string
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	UsedAt      pgtype.Timestamptz
	UsedBy      pgtype.UUID
	MemberID    pgtype.UUID
}

type Member struct {
	ID              pgtype.UUID
	HouseholdID     pgtype.UUID
	Name            string
	Role            string
	BirthYear       *int32
	Care            *string
	CapacityMinutes []int32
	AuthUserID      *string
	CreatedAt       pgtype.Timestamptz
}

type Occasion struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	Title       string
	Day         pgtype.Date
	Kind        string
	Yearly      bool
	CreatedAt   pgtype.Timestamptz
}

type Signal struct {
	HouseholdID pgtype.UUID
	TemplateID  string
	Kind        string
	Value       float64
	UpdatedAt   pgtype.Timestamptz
}

type TaskInstance struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	TemplateID  string
	ISOWeek     string
	Day         pgtype.Date
	Slot        string
	DurationMin int32
	HeadLoad    int32
	Deadline    pgtype.Date
	CreatedAt   pgtype.Timestamptz
}

type TaskTemplate struct {
	ID          string
	HouseholdID pgtype.UUID
	Source      string
	Version     string
	Definition  []byte
	CreatedAt   pgtype.Timestamptz
}

type WeekPlan struct {
	HouseholdID pgtype.UUID
	ISOWeek     string
	Skipped     []byte
	CreatedAt   pgtype.Timestamptz
}
