// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAssignment = `-- name: ClearAssignment :exec
DELETE FROM assignment WHERE task_instance_id = $1
`

// Abgegeben und noch niemand übernommen. Ein gültiger Zwischenzustand — siehe
// den LEFT JOIN in GetWeekPlan.
func (q *Queries) ClearAssignment(ctx context.Context, taskInstanceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearAssignment, taskInstanceID)
	return err
}

const deleteUntouchedTemplateTasksFrom = `-- name: DeleteUntouchedTemplateTasksFrom :exec
DELETE FROM task_instance t
WHERE t.household_id = $1
  AND t.iso_week = $2
  AND t.template_id = $3
  AND t.day >= $4
  AND NOT EXISTS (SELECT 1 FROM event e WHERE e.task_instance_id = t.id)
`

type DeleteUntouchedTemplateTasksFromParams struct {
	HouseholdID pgtype.UUID
	ISOWeek     string
	TemplateID  string
	Day         pgtype.Date
}

// Wie DeleteUntouchedWeekTasks, aber auf eine Vorlage und ab einem Tag
// eingegrenzt.
//
// Der Unterschied ist Absicht und nicht Sparsamkeit: Wer eine Absprache
// einträgt, will diese eine Aufgabe in dieser Woche sehen — und nicht, dass
// sich nebenbei umsortiert, wer am Freitag das Bad putzt. Ein Neurechnen der
// ganzen Woche wäre für diesen Wunsch ein zu grobes Werkzeug.
//
// Vergangene Tage bleiben unangetastet: Ein Kita-Termin von gestern früh ist
// keine Verabredung mehr, die man noch treffen könnte.
func (q *Queries) DeleteUntouchedTemplateTasksFrom(ctx context.Context, arg DeleteUntouchedTemplateTasksFromParams) error {
	_, err := q.db.Exec(ctx, deleteUntouchedTemplateTasksFrom,
		arg.HouseholdID,
		arg.ISOWeek,
		arg.TemplateID,
		arg.Day,
	)
	return err
}

const deleteUntouchedWeekTasks = `-- name: DeleteUntouchedWeekTasks :exec
DELETE FROM task_instance t
WHERE t.household_id = $1
  AND t.iso_week = $2
  AND NOT EXISTS (SELECT 1 FROM event e WHERE e.task_instance_id = t.id)
`

type DeleteUntouchedWeekTasksParams struct {
	HouseholdID pgtype.UUID
	ISOWeek     string
}

// Verwirft die Aufgaben einer Woche, an denen nichts hängt.
//
// Der Filter ist keine Vorsicht, sondern eine Konsequenz: event.task_instance_id
// ist ON DELETE SET NULL, und der Trigger event_kein_update verbietet jedes
// UPDATE auf event. Eine Aufgabe mit Ereignis zu löschen wirft also eine
// Ausnahme — die Datenbank lässt gar nicht zu, dass Neurechnen Geschehenes
// wegräumt.
//
// Daraus wird eine Produktregel: Was Spuren hinterlassen hat, bleibt. Was nur
// ein Vorschlag war, wird neu gerechnet.
func (q *Queries) DeleteUntouchedWeekTasks(ctx context.Context, arg DeleteUntouchedWeekTasksParams) error {
	_, err := q.db.Exec(ctx, deleteUntouchedWeekTasks, arg.HouseholdID, arg.ISOWeek)
	return err
}

const deleteWeek = `-- name: DeleteWeek :exec
DELETE FROM task_instance WHERE household_id = $1 AND iso_week = $2
`

type DeleteWeekParams struct {
	HouseholdID pgtype.UUID
	ISOWeek     string
}

// Ein Wochenplan wird ersetzt, nicht fortgeschrieben: Der Planer ist
// deterministisch, ein zweiter Lauf mit derselben Eingabe ergibt dasselbe.
// Die Zuteilungen hängen per ON DELETE CASCADE mit dran.
func (q *Queries) DeleteWeek(ctx context.Context, arg DeleteWeekParams) error {
	_, err := q.db.Exec(ctx, deleteWeek, arg.HouseholdID, arg.ISOWeek)
	return err
}

const getTaskForMember = `-- name: GetTaskForMember :one
SELECT
    t.id, t.household_id, t.template_id, t.iso_week, t.day,
    m.id AS member_id, m.role AS member_role,
    a.member_id AS assignee_id
FROM task_instance t
JOIN member m ON m.household_id = t.household_id AND m.auth_user_id = $2
LEFT JOIN assignment a ON a.task_instance_id = t.id
WHERE t.id = $1
`

type GetTaskForMemberParams struct {
	ID         pgtype.UUID
	AuthUserID *string
}

type GetTaskForMemberRow struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	TemplateID  string
	ISOWeek     string
	Day         pgtype.Date
	MemberID    pgtype.UUID
	MemberRole  string
	AssigneeID  pgtype.UUID
}

// Eine Aufgabe samt ihrem Haushalt — aber nur, wenn der Aufrufer in diesem
// Haushalt Mitglied ist.
//
// Die Berechtigungsprüfung steht im JOIN und nicht davor in Go: Eine Aufgabe
// aus einem fremden Haushalt gibt es für diesen Aufrufer nicht, und das soll
// nicht an einem vergessenen if hängen.
func (q *Queries) GetTaskForMember(ctx context.Context, arg GetTaskForMemberParams) (GetTaskForMemberRow, error) {
	row := q.db.QueryRow(ctx, getTaskForMember, arg.ID, arg.AuthUserID)
	var i GetTaskForMemberRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.TemplateID,
		&i.ISOWeek,
		&i.Day,
		&i.MemberID,
		&i.MemberRole,
		&i.AssigneeID,
	)
	return i, err
}

const getWeekPlan = `-- name: GetWeekPlan :many
SELECT
    t.id,
    t.template_id,
    t.day,
    t.slot,
    t.duration_min,
    t.head_load,
    t.deadline,
    tt.definition,
    a.member_id,
    a.reason_code,
    a.reason_previous,
    a.manual
FROM task_instance t
JOIN task_template tt ON tt.id = t.template_id
LEFT JOIN assignment a ON a.task_instance_id = t.id
WHERE t.household_id = $1 AND t.iso_week = $2
ORDER BY t.day, t.id
`

type GetWeekPlanParams struct {
	HouseholdID pgtype.UUID
	ISOWeek     string
}

type GetWeekPlanRow struct {
	ID             pgtype.UUID
	TemplateID     string
	Day            pgtype.Date
	Slot           string
	DurationMin    int32
	HeadLoad       int32
	Deadline       pgtype.Date
	Definition     []byte
	MemberID       pgtype.UUID
	ReasonCode     *string
	ReasonPrevious pgtype.UUID
	Manual         *bool
}

// Der gespeicherte Plan einer Woche, mit der Vorlage daneben.
//
// LEFT JOIN auf assignment mit Absicht: Eine Aufgabe ohne Zuständige ist ein
// gültiger Zustand — jemand hat sie abgegeben und noch niemand übernommen.
func (q *Queries) GetWeekPlan(ctx context.Context, arg GetWeekPlanParams) ([]GetWeekPlanRow, error) {
	rows, err := q.db.Query(ctx, getWeekPlan, arg.HouseholdID, arg.ISOWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWeekPlanRow{}
	for rows.Next() {
		var i GetWeekPlanRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Day,
			&i.Slot,
			&i.DurationMin,
			&i.HeadLoad,
			&i.Deadline,
			&i.Definition,
			&i.MemberID,
			&i.ReasonCode,
			&i.ReasonPrevious,
			&i.Manual,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWrittenWeek = `-- name: GetWrittenWeek :one
SELECT household_id, iso_week, skipped, created_at FROM week_plan WHERE household_id = $1 AND iso_week = $2
`

type GetWrittenWeekParams struct {
	HouseholdID pgtype.UUID
	ISOWeek     string
}

func (q *Queries) GetWrittenWeek(ctx context.Context, arg GetWrittenWeekParams) (WeekPlan, error) {
	row := q.db.QueryRow(ctx, getWrittenWeek, arg.HouseholdID, arg.ISOWeek)
	var i WeekPlan
	err := row.Scan(
		&i.HouseholdID,
		&i.ISOWeek,
		&i.Skipped,
		&i.CreatedAt,
	)
	return i, err
}

const insertAssignment = `-- name: InsertAssignment :exec
INSERT INTO assignment (task_instance_id, member_id, reason_code, reason_previous, manual)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAssignmentParams struct {
	TaskInstanceID pgtype.UUID
	MemberID       pgtype.UUID
	ReasonCode     string
	ReasonPrevious pgtype.UUID
	Manual         bool
}

func (q *Queries) InsertAssignment(ctx context.Context, arg InsertAssignmentParams) error {
	_, err := q.db.Exec(ctx, insertAssignment,
		arg.TaskInstanceID,
		arg.MemberID,
		arg.ReasonCode,
		arg.ReasonPrevious,
		arg.Manual,
	)
	return err
}

const insertTaskInstance = `-- name: InsertTaskInstance :one
INSERT INTO task_instance
    (household_id, template_id, iso_week, day, slot, duration_min, head_load, deadline)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertTaskInstanceParams struct {
	HouseholdID pgtype.UUID
	TemplateID  string
	ISOWeek     string
	Day         pgtype.Date
	Slot        string
	DurationMin int32
	HeadLoad    int32
	Deadline    pgtype.Date
}

func (q *Queries) InsertTaskInstance(ctx context.Context, arg InsertTaskInstanceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertTaskInstance,
		arg.HouseholdID,
		arg.TemplateID,
		arg.ISOWeek,
		arg.Day,
		arg.Slot,
		arg.DurationMin,
		arg.HeadLoad,
		arg.Deadline,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listDoneTasks = `-- name: ListDoneTasks :many
SELECT DISTINCT ON (e.task_instance_id)
    e.task_instance_id, e.member_id, e.occurred_at, e.kind
FROM event e
JOIN task_instance t ON t.id = e.task_instance_id
WHERE t.household_id = $1
  AND t.iso_week = $2
  AND e.kind IN ('erledigt', 'wieder_geoeffnet')
ORDER BY e.task_instance_id, e.occurred_at DESC, e.id DESC
`

type ListDoneTasksParams struct {
	HouseholdID pgtype.UUID
	ISOWeek     string
}

type ListDoneTasksRow struct {
	TaskInstanceID pgtype.UUID
	MemberID       pgtype.UUID
	OccurredAt     pgtype.Timestamptz
	Kind           string
}

// Welche Aufgaben dieser Woche erledigt sind.
//
// Die Wahrheit steht im Ereignisprotokoll, nicht in einer Spalte auf der
// Aufgabe. Ein Häkchen wäre eine zweite Wahrheit neben dem Protokoll — und
// das Protokoll ist die, die auch „wieder geöffnet" erzählen kann.
func (q *Queries) ListDoneTasks(ctx context.Context, arg ListDoneTasksParams) ([]ListDoneTasksRow, error) {
	rows, err := q.db.Query(ctx, listDoneTasks, arg.HouseholdID, arg.ISOWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDoneTasksRow{}
	for rows.Next() {
		var i ListDoneTasksRow
		if err := rows.Scan(
			&i.TaskInstanceID,
			&i.MemberID,
			&i.OccurredAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStruckTasks = `-- name: ListStruckTasks :many
SELECT DISTINCT ON (e.task_instance_id)
    e.task_instance_id, e.member_id, e.occurred_at, e.kind
FROM event e
JOIN task_instance t ON t.id = e.task_instance_id
WHERE t.household_id = $1
  AND t.iso_week = $2
  AND e.kind IN ('gestrichen', 'wieder_eingeplant')
ORDER BY e.task_instance_id, e.occurred_at DESC, e.id DESC
`

type ListStruckTasksParams struct {
	HouseholdID pgtype.UUID
	ISOWeek     string
}

type ListStruckTasksRow struct {
	TaskInstanceID pgtype.UUID
	MemberID       pgtype.UUID
	OccurredAt     pgtype.Timestamptz
	Kind           string
}

// Welche Aufgaben dieser Woche gestrichen sind.
//
// Dieselbe Bauart wie ListDoneTasks, mit dem anderen Ereignispaar: Das
// jüngste Ereignis je Aufgabe entscheidet, und `wieder_eingeplant` hebt
// `gestrichen` auf. Gestrichen heißt: für DIESE Woche nicht — die Vorlage
// bleibt unangetastet und ist nächste Woche wieder dran.
func (q *Queries) ListStruckTasks(ctx context.Context, arg ListStruckTasksParams) ([]ListStruckTasksRow, error) {
	rows, err := q.db.Query(ctx, listStruckTasks, arg.HouseholdID, arg.ISOWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStruckTasksRow{}
	for rows.Next() {
		var i ListStruckTasksRow
		if err := rows.Scan(
			&i.TaskInstanceID,
			&i.MemberID,
			&i.OccurredAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateTaskDays = `-- name: ListTemplateTaskDays :many
SELECT day FROM task_instance
WHERE household_id = $1 AND iso_week = $2 AND template_id = $3
`

type ListTemplateTaskDaysParams struct {
	HouseholdID pgtype.UUID
	ISOWeek     string
	TemplateID  string
}

// Die Tage, an denen diese Vorlage in dieser Woche noch steht — nach dem
// Verwerfen also die, an denen schon etwas geschehen ist.
func (q *Queries) ListTemplateTaskDays(ctx context.Context, arg ListTemplateTaskDaysParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listTemplateTaskDays, arg.HouseholdID, arg.ISOWeek, arg.TemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var day pgtype.Date
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeekTaskKeys = `-- name: ListWeekTaskKeys :many
SELECT template_id, day FROM task_instance
WHERE household_id = $1 AND iso_week = $2
`

type ListWeekTaskKeysParams struct {
	HouseholdID pgtype.UUID
	ISOWeek     string
}

type ListWeekTaskKeysRow struct {
	TemplateID string
	Day        pgtype.Date
}

// Was von einer Woche übrig ist, nach dem Verwerfen: Vorlage und Tag. Damit
// rechnet das Neuschreiben nichts doppelt hin.
func (q *Queries) ListWeekTaskKeys(ctx context.Context, arg ListWeekTaskKeysParams) ([]ListWeekTaskKeysRow, error) {
	rows, err := q.db.Query(ctx, listWeekTaskKeys, arg.HouseholdID, arg.ISOWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWeekTaskKeysRow{}
	for rows.Next() {
		var i ListWeekTaskKeysRow
		if err := rows.Scan(&i.TemplateID, &i.Day); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWeekWritten = `-- name: MarkWeekWritten :one
INSERT INTO week_plan (household_id, iso_week, skipped)
VALUES ($1, $2, $3)
ON CONFLICT (household_id, iso_week) DO NOTHING
RETURNING household_id, iso_week, skipped, created_at
`

type MarkWeekWrittenParams struct {
	HouseholdID pgtype.UUID
	ISOWeek     string
	Skipped     []byte
}

// Schreibt die Marke „diese Woche steht" — und nur der erste Aufrufer
// gewinnt. ON CONFLICT DO NOTHING liefert dann keine Zeile zurück, und genau
// daran erkennt der zweite, dass er lesen statt schreiben soll.
func (q *Queries) MarkWeekWritten(ctx context.Context, arg MarkWeekWrittenParams) (WeekPlan, error) {
	row := q.db.QueryRow(ctx, markWeekWritten, arg.HouseholdID, arg.ISOWeek, arg.Skipped)
	var i WeekPlan
	err := row.Scan(
		&i.HouseholdID,
		&i.ISOWeek,
		&i.Skipped,
		&i.CreatedAt,
	)
	return i, err
}

const reassignTask = `-- name: ReassignTask :exec
UPDATE assignment
SET member_id = $2, manual = true
WHERE task_instance_id = $1
`

type ReassignTaskParams struct {
	TaskInstanceID pgtype.UUID
	MemberID       pgtype.UUID
}

// Von Hand umverteilt. manual = true ist die eigentliche Information: Jede
// Korrektur sagt, wo der Planer danebenlag.
func (q *Queries) ReassignTask(ctx context.Context, arg ReassignTaskParams) error {
	_, err := q.db.Exec(ctx, reassignTask, arg.TaskInstanceID, arg.MemberID)
	return err
}

const setAssignment = `-- name: SetAssignment :exec
INSERT INTO assignment (task_instance_id, member_id, reason_code, reason_previous, manual)
VALUES ($1, $2, $3, $4, true)
`

type SetAssignmentParams struct {
	TaskInstanceID pgtype.UUID
	MemberID       pgtype.UUID
	ReasonCode     string
	ReasonPrevious pgtype.UUID
}

// Nach einer Abgabe: neue Zuständige, neue Begründung, von Hand markiert.
func (q *Queries) SetAssignment(ctx context.Context, arg SetAssignmentParams) error {
	_, err := q.db.Exec(ctx, setAssignment,
		arg.TaskInstanceID,
		arg.MemberID,
		arg.ReasonCode,
		arg.ReasonPrevious,
	)
	return err
}

const updateWeekSkipped = `-- name: UpdateWeekSkipped :exec
UPDATE week_plan SET skipped = $3
WHERE household_id = $1 AND iso_week = $2
`

type UpdateWeekSkippedParams struct {
	HouseholdID pgtype.UUID
	ISOWeek     string
	Skipped     []byte
}

func (q *Queries) UpdateWeekSkipped(ctx context.Context, arg UpdateWeekSkippedParams) error {
	_, err := q.db.Exec(ctx, updateWeekSkipped, arg.HouseholdID, arg.ISOWeek, arg.Skipped)
	return err
}
