// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWeek = `-- name: DeleteWeek :exec
DELETE FROM task_instance WHERE household_id = $1 AND iso_week = $2
`

type DeleteWeekParams struct {
	HouseholdID pgtype.UUID
	ISOWeek     string
}

// Ein Wochenplan wird ersetzt, nicht fortgeschrieben: Der Planer ist
// deterministisch, ein zweiter Lauf mit derselben Eingabe ergibt dasselbe.
// Die Zuteilungen hängen per ON DELETE CASCADE mit dran.
func (q *Queries) DeleteWeek(ctx context.Context, arg DeleteWeekParams) error {
	_, err := q.db.Exec(ctx, deleteWeek, arg.HouseholdID, arg.ISOWeek)
	return err
}

const getWeekPlan = `-- name: GetWeekPlan :many
SELECT
    t.id,
    t.template_id,
    t.day,
    t.slot,
    t.duration_min,
    t.head_load,
    t.deadline,
    tt.definition,
    a.member_id,
    a.reason_code,
    a.reason_previous,
    a.manual
FROM task_instance t
JOIN task_template tt ON tt.id = t.template_id
LEFT JOIN assignment a ON a.task_instance_id = t.id
WHERE t.household_id = $1 AND t.iso_week = $2
ORDER BY t.day, t.id
`

type GetWeekPlanParams struct {
	HouseholdID pgtype.UUID
	ISOWeek     string
}

type GetWeekPlanRow struct {
	ID             pgtype.UUID
	TemplateID     string
	Day            pgtype.Date
	Slot           string
	DurationMin    int32
	HeadLoad       int32
	Deadline       pgtype.Date
	Definition     []byte
	MemberID       pgtype.UUID
	ReasonCode     *string
	ReasonPrevious pgtype.UUID
	Manual         *bool
}

// Der gespeicherte Plan einer Woche, mit der Vorlage daneben.
//
// LEFT JOIN auf assignment mit Absicht: Eine Aufgabe ohne Zuständige ist ein
// gültiger Zustand — jemand hat sie abgegeben und noch niemand übernommen.
func (q *Queries) GetWeekPlan(ctx context.Context, arg GetWeekPlanParams) ([]GetWeekPlanRow, error) {
	rows, err := q.db.Query(ctx, getWeekPlan, arg.HouseholdID, arg.ISOWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWeekPlanRow{}
	for rows.Next() {
		var i GetWeekPlanRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Day,
			&i.Slot,
			&i.DurationMin,
			&i.HeadLoad,
			&i.Deadline,
			&i.Definition,
			&i.MemberID,
			&i.ReasonCode,
			&i.ReasonPrevious,
			&i.Manual,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAssignment = `-- name: InsertAssignment :exec
INSERT INTO assignment (task_instance_id, member_id, reason_code, reason_previous, manual)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAssignmentParams struct {
	TaskInstanceID pgtype.UUID
	MemberID       pgtype.UUID
	ReasonCode     string
	ReasonPrevious pgtype.UUID
	Manual         bool
}

func (q *Queries) InsertAssignment(ctx context.Context, arg InsertAssignmentParams) error {
	_, err := q.db.Exec(ctx, insertAssignment,
		arg.TaskInstanceID,
		arg.MemberID,
		arg.ReasonCode,
		arg.ReasonPrevious,
		arg.Manual,
	)
	return err
}

const insertTaskInstance = `-- name: InsertTaskInstance :one
INSERT INTO task_instance
    (household_id, template_id, iso_week, day, slot, duration_min, head_load, deadline)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertTaskInstanceParams struct {
	HouseholdID pgtype.UUID
	TemplateID  string
	ISOWeek     string
	Day         pgtype.Date
	Slot        string
	DurationMin int32
	HeadLoad    int32
	Deadline    pgtype.Date
}

func (q *Queries) InsertTaskInstance(ctx context.Context, arg InsertTaskInstanceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertTaskInstance,
		arg.HouseholdID,
		arg.TemplateID,
		arg.ISOWeek,
		arg.Day,
		arg.Slot,
		arg.DurationMin,
		arg.HeadLoad,
		arg.Deadline,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const reassignTask = `-- name: ReassignTask :exec
UPDATE assignment
SET member_id = $2, manual = true
WHERE task_instance_id = $1
`

type ReassignTaskParams struct {
	TaskInstanceID pgtype.UUID
	MemberID       pgtype.UUID
}

// Von Hand umverteilt. manual = true ist die eigentliche Information: Jede
// Korrektur sagt, wo der Planer danebenlag.
func (q *Queries) ReassignTask(ctx context.Context, arg ReassignTaskParams) error {
	_, err := q.db.Exec(ctx, reassignTask, arg.TaskInstanceID, arg.MemberID)
	return err
}
