// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rueckmeldung.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertFeedback = `-- name: InsertFeedback :exec
INSERT INTO feedback (household_id, member_id, art, text, kontext)
VALUES ($1, $2, $3, $4, $5)
`

type InsertFeedbackParams struct {
	HouseholdID pgtype.UUID
	MemberID    pgtype.UUID
	Art         string
	Text        string
	Kontext     string
}

// Eine Rückmeldung aus der App. Jedes Mitglied darf melden, nicht nur die
// planenden — die ausführenden sehen die Stellen, an denen es klemmt, zuerst.
func (q *Queries) InsertFeedback(ctx context.Context, arg InsertFeedbackParams) error {
	_, err := q.db.Exec(ctx, insertFeedback,
		arg.HouseholdID,
		arg.MemberID,
		arg.Art,
		arg.Text,
		arg.Kontext,
	)
	return err
}

const listFeedback = `-- name: ListFeedback :many
SELECT f.id, f.art, f.text, f.kontext, f.created_at, m.name AS wer
FROM feedback f
LEFT JOIN member m ON m.id = f.member_id
WHERE f.household_id = $1
ORDER BY f.created_at DESC
LIMIT 50
`

type ListFeedbackRow struct {
	ID        pgtype.UUID
	Art       string
	Text      string
	Kontext   string
	CreatedAt pgtype.Timestamptz
	Wer       *string
}

// Was dieser Haushalt gemeldet hat, das Neueste zuerst.
//
// Mit Namen daneben: Eine Liste von Sätzen ohne Absender ist bei der
// Auswertung nur halb so viel wert — „das hat sie gesagt" und „das hat er
// gesagt" sind zwei verschiedene Befunde.
func (q *Queries) ListFeedback(ctx context.Context, householdID pgtype.UUID) ([]ListFeedbackRow, error) {
	rows, err := q.db.Query(ctx, listFeedback, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedbackRow{}
	for rows.Next() {
		var i ListFeedbackRow
		if err := rows.Scan(
			&i.ID,
			&i.Art,
			&i.Text,
			&i.Kontext,
			&i.CreatedAt,
			&i.Wer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
