// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSignals = `-- name: ListSignals :many
SELECT household_id, template_id, kind, value, updated_at FROM signal WHERE household_id = $1 ORDER BY template_id, kind
`

func (q *Queries) ListSignals(ctx context.Context, householdID pgtype.UUID) ([]Signal, error) {
	rows, err := q.db.Query(ctx, listSignals, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signal{}
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.HouseholdID,
			&i.TemplateID,
			&i.Kind,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSignal = `-- name: UpsertSignal :exec
INSERT INTO signal (household_id, template_id, kind, value, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (household_id, template_id, kind)
DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type UpsertSignalParams struct {
	HouseholdID pgtype.UUID
	TemplateID  string
	Kind        string
	Value       float64
}

// Lernwerte sind ableitbar, nicht Quelle: Diese Tabelle darf jederzeit aus dem
// Protokoll neu berechnet werden.
func (q *Queries) UpsertSignal(ctx context.Context, arg UpsertSignalParams) error {
	_, err := q.db.Exec(ctx, upsertSignal,
		arg.HouseholdID,
		arg.TemplateID,
		arg.Kind,
		arg.Value,
	)
	return err
}
