// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: template.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTemplatesForHousehold = `-- name: ListTemplatesForHousehold :many
SELECT id, household_id, source, version, definition, created_at FROM task_template
WHERE household_id IS NULL OR household_id = $1
ORDER BY id
`

// Kuratierte Vorlagen gelten für alle (household_id IS NULL), dazu die
// eigenen. Die Reihenfolge ist stabil, damit der Planer deterministisch bleibt.
func (q *Queries) ListTemplatesForHousehold(ctx context.Context, householdID pgtype.UUID) ([]TaskTemplate, error) {
	rows, err := q.db.Query(ctx, listTemplatesForHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskTemplate{}
	for rows.Next() {
		var i TaskTemplate
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Source,
			&i.Version,
			&i.Definition,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCuratedTemplate = `-- name: UpsertCuratedTemplate :exec
INSERT INTO task_template (id, household_id, source, version, definition)
VALUES ($1, NULL, 'kuratiert', $2, $3)
ON CONFLICT (id) DO UPDATE
    SET version    = EXCLUDED.version,
        definition = EXCLUDED.definition
`

type UpsertCuratedTemplateParams struct {
	ID         string
	Version    string
	Definition []byte
}

// Import der Bibliothek aus dem Repo. Beim Start oder in einem eigenen
// Kommando aufgerufen; die Datei bleibt die Quelle, die Tabelle ist die Kopie.
func (q *Queries) UpsertCuratedTemplate(ctx context.Context, arg UpsertCuratedTemplateParams) error {
	_, err := q.db.Exec(ctx, upsertCuratedTemplate, arg.ID, arg.Version, arg.Definition)
	return err
}
