//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AufgabeArt.
const (
	Ausfuehrung  AufgabeArt = "ausfuehrung"
	Organisation AufgabeArt = "organisation"
)

// Valid indicates whether the value is a known member of the AufgabeArt enum.
func (e AufgabeArt) Valid() bool {
	switch e {
	case Ausfuehrung:
		return true
	case Organisation:
		return true
	default:
		return false
	}
}

// Defines values for AufgabeZeitfenster.
const (
	Abends  AufgabeZeitfenster = "abends"
	Egal    AufgabeZeitfenster = "egal"
	Morgens AufgabeZeitfenster = "morgens"
)

// Valid indicates whether the value is a known member of the AufgabeZeitfenster enum.
func (e AufgabeZeitfenster) Valid() bool {
	switch e {
	case Abends:
		return true
	case Egal:
		return true
	case Morgens:
		return true
	default:
		return false
	}
}

// Defines values for BegruendungCode.
const (
	Ausgleich           BegruendungCode = "ausgleich"
	EigeneAufgabe       BegruendungCode = "eigene_aufgabe"
	EinzigeMoeglichkeit BegruendungCode = "einzige_moeglichkeit"
	FestePerson         BegruendungCode = "feste_person"
	Frist               BegruendungCode = "frist"
	Rotation            BegruendungCode = "rotation"
)

// Valid indicates whether the value is a known member of the BegruendungCode enum.
func (e BegruendungCode) Valid() bool {
	switch e {
	case Ausgleich:
		return true
	case EigeneAufgabe:
		return true
	case EinzigeMoeglichkeit:
		return true
	case FestePerson:
		return true
	case Frist:
		return true
	case Rotation:
		return true
	default:
		return false
	}
}

// Defines values for Kategorie.
const (
	Aussen     Kategorie = "aussen"
	Kind       Kategorie = "kind"
	Kueche     Kategorie = "kueche"
	Reinigung  Kategorie = "reinigung"
	Sozial     Kategorie = "sozial"
	Termine    Kategorie = "termine"
	Verwaltung Kategorie = "verwaltung"
	Vorrat     Kategorie = "vorrat"
	Waesche    Kategorie = "waesche"
	Wartung    Kategorie = "wartung"
)

// Valid indicates whether the value is a known member of the Kategorie enum.
func (e Kategorie) Valid() bool {
	switch e {
	case Aussen:
		return true
	case Kind:
		return true
	case Kueche:
		return true
	case Reinigung:
		return true
	case Sozial:
		return true
	case Termine:
		return true
	case Verwaltung:
		return true
	case Vorrat:
		return true
	case Waesche:
		return true
	case Wartung:
		return true
	default:
		return false
	}
}

// Defines values for MitgliedRolle.
const (
	Ausfuehrend MitgliedRolle = "ausfuehrend"
	Betreut     MitgliedRolle = "betreut"
	Planend     MitgliedRolle = "planend"
)

// Valid indicates whether the value is a known member of the MitgliedRolle enum.
func (e MitgliedRolle) Valid() bool {
	switch e {
	case Ausfuehrend:
		return true
	case Betreut:
		return true
	case Planend:
		return true
	default:
		return false
	}
}

// Defines values for UebersprungenGrund.
const (
	Abgewaehlt      UebersprungenGrund = "abgewaehlt"
	GiltNicht       UebersprungenGrund = "gilt_nicht"
	KeineKapazitaet UebersprungenGrund = "keine_kapazitaet"
	NichtFaellig    UebersprungenGrund = "nicht_faellig"
	NiemandGeeignet UebersprungenGrund = "niemand_geeignet"
	Startdichte     UebersprungenGrund = "startdichte"
)

// Valid indicates whether the value is a known member of the UebersprungenGrund enum.
func (e UebersprungenGrund) Valid() bool {
	switch e {
	case Abgewaehlt:
		return true
	case GiltNicht:
		return true
	case KeineKapazitaet:
		return true
	case NichtFaellig:
		return true
	case NiemandGeeignet:
		return true
	case Startdichte:
		return true
	default:
		return false
	}
}

// Aufgabe defines model for Aufgabe.
type Aufgabe struct {
	Art AufgabeArt `json:"art"`

	// Begruendung Maschinenlesbar. Das Sprachmodell formuliert daraus später einen Satz
	// für die Oberfläche — es erfindet keine Begründung, es übersetzt eine.
	Begruendung Begruendung `json:"begruendung"`

	// DauerMin Example: 35
	DauerMin int `json:"dauer_min"`

	// Frist gesetzt, wenn die Aufgabe eine echte Frist hat
	Frist     *string   `json:"frist,omitempty"`
	Kategorie Kategorie `json:"kategorie"`

	// Kopflast Planungs- und Erinnerungsaufwand, unabhängig von der Dauer
	Kopflast int `json:"kopflast"`

	// Tag Kalendertag ohne Uhrzeit und ohne Zeitzone (ADR-0002). Über die
	// Grenze geht die ISO-Zeichenkette; die Anzeige rechnet sie in
	// Europe/Berlin um.
	//
	//
	// Example: 2026-09-19
	Tag string `json:"tag"`

	// Titel Example: Bad putzen
	Titel string `json:"titel"`

	// VorlageId Example: t-bad
	VorlageId   string             `json:"vorlage_id"`
	Zeitfenster AufgabeZeitfenster `json:"zeitfenster"`

	// Zustaendig Kennung des Mitglieds
	//
	// Example: m-ben
	Zustaendig string `json:"zustaendig"`
}

// AufgabeArt defines model for Aufgabe.Art.
type AufgabeArt string

// AufgabeZeitfenster defines model for Aufgabe.Zeitfenster.
type AufgabeZeitfenster string

// Begruendung Maschinenlesbar. Das Sprachmodell formuliert daraus später einen Satz
// für die Oberfläche — es erfindet keine Begründung, es übersetzt eine.
type Begruendung struct {
	Code BegruendungCode `json:"code"`

	// ZuletztBei bei `rotation` die Person, die die Aufgabe zuletzt hatte
	ZuletztBei *string `json:"zuletzt_bei,omitempty"`
}

// BegruendungCode defines model for Begruendung.Code.
type BegruendungCode string

// Bilanz defines model for Bilanz.
type Bilanz struct {
	Aufgaben int `json:"aufgaben"`

	// AuslastungProzent Verplante Minuten im Verhältnis zur verfügbaren Zeit. Gerechnet
	// wird mit den reinen Minuten — Kopflast kostet Aufmerksamkeit,
	// aber keine Uhrzeit (ADR-0004).
	AuslastungProzent int `json:"auslastung_prozent"`

	// Gewichtet Minuten + Kopflast × 15
	Gewichtet int `json:"gewichtet"`

	// KapazitaetMinuten verfügbare Minuten der ganzen Woche
	KapazitaetMinuten int    `json:"kapazitaet_minuten"`
	Kopflast          int    `json:"kopflast"`
	Minuten           int    `json:"minuten"`
	MitgliedId        string `json:"mitglied_id"`
}

// Fehler defines model for Fehler.
type Fehler struct {
	// Fehler für Menschen lesbar, deutsch
	//
	// Example: die Woche "2026-W99" liegt außerhalb von 1..53
	Fehler string `json:"fehler"`
}

// Haushalt defines model for Haushalt.
type Haushalt struct {
	// Id Example: familie-a
	Id         string     `json:"id"`
	Mitglieder []Mitglied `json:"mitglieder"`

	// Name Example: Familie A
	Name string `json:"name"`
}

// Ich Absichtlich schmal: Hier steht nur, was der Aussteller signiert hat.
// Welche Person in welchem Haushalt dahintersteckt, ist eine Frage an die
// Datenbank und kommt mit dem Onboarding dazu.
type Ich struct {
	Angemeldet bool    `json:"angemeldet"`
	Email      *string `json:"email,omitempty"`
	Name       *string `json:"name,omitempty"`

	// Subject Nutzerkennung des Anmeldedienstes
	Subject *string `json:"subject,omitempty"`
}

// Kategorie defines model for Kategorie.
type Kategorie string

// Mitglied defines model for Mitglied.
type Mitglied struct {
	// Id Example: m-anna
	Id string `json:"id"`

	// Name Example: Anna
	Name string `json:"name"`

	// Rolle `planend` plant und führt aus, `ausfuehrend` führt nur aus,
	// `betreut` erzeugt Arbeit ohne welche zu übernehmen.
	Rolle MitgliedRolle `json:"rolle"`
}

// MitgliedRolle `planend` plant und führt aus, `ausfuehrend` führt nur aus,
// `betreut` erzeugt Arbeit ohne welche zu übernehmen.
type MitgliedRolle string

// Uebersprungen defines model for Uebersprungen.
type Uebersprungen struct {
	Grund     UebersprungenGrund `json:"grund"`
	Titel     string             `json:"titel"`
	VorlageId string             `json:"vorlage_id"`
}

// UebersprungenGrund defines model for Uebersprungen.Grund.
type UebersprungenGrund string

// Version defines model for Version.
type Version struct {
	// Version kurze Commit-Kennung oder "dev"
	//
	// Example: f18a432
	Version string `json:"version"`
}

// Wochenplan defines model for Wochenplan.
type Wochenplan struct {
	Aufgaben []Aufgabe `json:"aufgaben"`

	// Bilanz eine Zeile je Person, die Aufgaben übernehmen kann
	Bilanz   []Bilanz `json:"bilanz"`
	Haushalt Haushalt `json:"haushalt"`

	// Uebersprungen Was nicht im Plan steht, mit Grund. Ohne dieses Feld könnte die
	// App nicht erklären, warum etwas fehlt.
	Uebersprungen []Uebersprungen `json:"uebersprungen"`

	// Woche Example: 2026-W38
	Woche string `json:"woche"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListHaushalte Verfügbare Haushalte
	// (GET /api/haushalte)
	ListHaushalte(w http.ResponseWriter, r *http.Request)
	// GetWochenplan Wochenplan eines Haushalts
	// (GET /api/haushalte/{haushaltId}/plan/{woche})
	GetWochenplan(w http.ResponseWriter, r *http.Request, haushaltId string, woche string)
	// GetIch Wer fragt
	// (GET /api/ich)
	GetIch(w http.ResponseWriter, r *http.Request)
	// GetVersion Welcher Stand läuft gerade
	// (GET /api/version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListHaushalte operation middleware
func (siw *ServerInterfaceWrapper) ListHaushalte(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHaushalte(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWochenplan operation middleware
func (siw *ServerInterfaceWrapper) GetWochenplan(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "haushaltId" -------------
	var haushaltId string

	err = runtime.BindStyledParameterWithOptions("simple", "haushaltId", r.PathValue("haushaltId"), &haushaltId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "haushaltId", Err: err})
		return
	}

	// ------------- Path parameter "woche" -------------
	var woche string

	err = runtime.BindStyledParameterWithOptions("simple", "woche", r.PathValue("woche"), &woche, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "woche", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWochenplan(w, r, haushaltId, woche)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIch operation middleware
func (siw *ServerInterfaceWrapper) GetIch(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/version", wrapper.GetVersion)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/ich", wrapper.GetIch)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/haushalte", wrapper.ListHaushalte)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/haushalte/{haushaltId}/plan/{woche}", wrapper.GetWochenplan)

	return m
}

type ListHaushalteRequestObject struct {
}

type ListHaushalteResponseObject interface {
	VisitListHaushalteResponse(w http.ResponseWriter) error
}

type ListHaushalte200JSONResponse []Haushalt

func (response ListHaushalte200JSONResponse) VisitListHaushalteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetWochenplanRequestObject struct {
	HaushaltId string `json:"haushaltId"`
	Woche      string `json:"woche"`
}

type GetWochenplanResponseObject interface {
	VisitGetWochenplanResponse(w http.ResponseWriter) error
}

type GetWochenplan200JSONResponse Wochenplan

func (response GetWochenplan200JSONResponse) VisitGetWochenplanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetWochenplan400JSONResponse Fehler

func (response GetWochenplan400JSONResponse) VisitGetWochenplanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetWochenplan404JSONResponse Fehler

func (response GetWochenplan404JSONResponse) VisitGetWochenplanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetIchRequestObject struct {
}

type GetIchResponseObject interface {
	VisitGetIchResponse(w http.ResponseWriter) error
}

type GetIch200JSONResponse Ich

func (response GetIch200JSONResponse) VisitGetIchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse Version

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListHaushalte Verfügbare Haushalte
	// (GET /api/haushalte)
	ListHaushalte(ctx context.Context, request ListHaushalteRequestObject) (ListHaushalteResponseObject, error)
	// GetWochenplan Wochenplan eines Haushalts
	// (GET /api/haushalte/{haushaltId}/plan/{woche})
	GetWochenplan(ctx context.Context, request GetWochenplanRequestObject) (GetWochenplanResponseObject, error)
	// GetIch Wer fragt
	// (GET /api/ich)
	GetIch(ctx context.Context, request GetIchRequestObject) (GetIchResponseObject, error)
	// GetVersion Welcher Stand läuft gerade
	// (GET /api/version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListHaushalte operation middleware
func (sh *strictHandler) ListHaushalte(w http.ResponseWriter, r *http.Request) {
	var request ListHaushalteRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListHaushalte(ctx, request.(ListHaushalteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListHaushalte")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListHaushalteResponseObject); ok {
		if err := validResponse.VisitListHaushalteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWochenplan operation middleware
func (sh *strictHandler) GetWochenplan(w http.ResponseWriter, r *http.Request, haushaltId string, woche string) {
	var request GetWochenplanRequestObject

	request.HaushaltId = haushaltId
	request.Woche = woche

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWochenplan(ctx, request.(GetWochenplanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWochenplan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWochenplanResponseObject); ok {
		if err := validResponse.VisitGetWochenplanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetIch operation middleware
func (sh *strictHandler) GetIch(w http.ResponseWriter, r *http.Request) {
	var request GetIchRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetIch(ctx, request.(GetIchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetIchResponseObject); ok {
		if err := validResponse.VisitGetIchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request) {
	var request GetVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
