//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AufgabeArt.
const (
	Ausfuehrung  AufgabeArt = "ausfuehrung"
	Organisation AufgabeArt = "organisation"
)

// Valid indicates whether the value is a known member of the AufgabeArt enum.
func (e AufgabeArt) Valid() bool {
	switch e {
	case Ausfuehrung:
		return true
	case Organisation:
		return true
	default:
		return false
	}
}

// Defines values for AufgabeZeitfenster.
const (
	Abends  AufgabeZeitfenster = "abends"
	Egal    AufgabeZeitfenster = "egal"
	Morgens AufgabeZeitfenster = "morgens"
)

// Valid indicates whether the value is a known member of the AufgabeZeitfenster enum.
func (e AufgabeZeitfenster) Valid() bool {
	switch e {
	case Abends:
		return true
	case Egal:
		return true
	case Morgens:
		return true
	default:
		return false
	}
}

// Defines values for BegruendungCode.
const (
	Ausgleich           BegruendungCode = "ausgleich"
	EigeneAufgabe       BegruendungCode = "eigene_aufgabe"
	EinzigeMoeglichkeit BegruendungCode = "einzige_moeglichkeit"
	FestePerson         BegruendungCode = "feste_person"
	Frist               BegruendungCode = "frist"
	Rotation            BegruendungCode = "rotation"
)

// Valid indicates whether the value is a known member of the BegruendungCode enum.
func (e BegruendungCode) Valid() bool {
	switch e {
	case Ausgleich:
		return true
	case EigeneAufgabe:
		return true
	case EinzigeMoeglichkeit:
		return true
	case FestePerson:
		return true
	case Frist:
		return true
	case Rotation:
		return true
	default:
		return false
	}
}

// Defines values for EinladungRolle.
const (
	EinladungRolleAusfuehrend EinladungRolle = "ausfuehrend"
	EinladungRollePlanend     EinladungRolle = "planend"
)

// Valid indicates whether the value is a known member of the EinladungRolle enum.
func (e EinladungRolle) Valid() bool {
	switch e {
	case EinladungRolleAusfuehrend:
		return true
	case EinladungRollePlanend:
		return true
	default:
		return false
	}
}

// Defines values for HaushaltMeineRolle.
const (
	HaushaltMeineRolleAusfuehrend HaushaltMeineRolle = "ausfuehrend"
	HaushaltMeineRolleBetreut     HaushaltMeineRolle = "betreut"
	HaushaltMeineRollePlanend     HaushaltMeineRolle = "planend"
)

// Valid indicates whether the value is a known member of the HaushaltMeineRolle enum.
func (e HaushaltMeineRolle) Valid() bool {
	switch e {
	case HaushaltMeineRolleAusfuehrend:
		return true
	case HaushaltMeineRolleBetreut:
		return true
	case HaushaltMeineRollePlanend:
		return true
	default:
		return false
	}
}

// Defines values for Kategorie.
const (
	Aussen     Kategorie = "aussen"
	Kind       Kategorie = "kind"
	Kueche     Kategorie = "kueche"
	Reinigung  Kategorie = "reinigung"
	Sozial     Kategorie = "sozial"
	Termine    Kategorie = "termine"
	Verwaltung Kategorie = "verwaltung"
	Vorrat     Kategorie = "vorrat"
	Waesche    Kategorie = "waesche"
	Wartung    Kategorie = "wartung"
)

// Valid indicates whether the value is a known member of the Kategorie enum.
func (e Kategorie) Valid() bool {
	switch e {
	case Aussen:
		return true
	case Kind:
		return true
	case Kueche:
		return true
	case Reinigung:
		return true
	case Sozial:
		return true
	case Termine:
		return true
	case Verwaltung:
		return true
	case Vorrat:
		return true
	case Waesche:
		return true
	case Wartung:
		return true
	default:
		return false
	}
}

// Defines values for MitgliedRolle.
const (
	MitgliedRolleAusfuehrend MitgliedRolle = "ausfuehrend"
	MitgliedRolleBetreut     MitgliedRolle = "betreut"
	MitgliedRollePlanend     MitgliedRolle = "planend"
)

// Valid indicates whether the value is a known member of the MitgliedRolle enum.
func (e MitgliedRolle) Valid() bool {
	switch e {
	case MitgliedRolleAusfuehrend:
		return true
	case MitgliedRolleBetreut:
		return true
	case MitgliedRollePlanend:
		return true
	default:
		return false
	}
}

// Defines values for NeuerHaushaltWohnform.
const (
	Haus    NeuerHaushaltWohnform = "haus"
	Wohnung NeuerHaushaltWohnform = "wohnung"
)

// Valid indicates whether the value is a known member of the NeuerHaushaltWohnform enum.
func (e NeuerHaushaltWohnform) Valid() bool {
	switch e {
	case Haus:
		return true
	case Wohnung:
		return true
	default:
		return false
	}
}

// Defines values for NeuesMitgliedRolle.
const (
	NeuesMitgliedRolleAusfuehrend NeuesMitgliedRolle = "ausfuehrend"
	NeuesMitgliedRolleBetreut     NeuesMitgliedRolle = "betreut"
	NeuesMitgliedRollePlanend     NeuesMitgliedRolle = "planend"
)

// Valid indicates whether the value is a known member of the NeuesMitgliedRolle enum.
func (e NeuesMitgliedRolle) Valid() bool {
	switch e {
	case NeuesMitgliedRolleAusfuehrend:
		return true
	case NeuesMitgliedRolleBetreut:
		return true
	case NeuesMitgliedRollePlanend:
		return true
	default:
		return false
	}
}

// Defines values for NeuesMitgliedZeit.
const (
	Keine  NeuesMitgliedZeit = "keine"
	Mittel NeuesMitgliedZeit = "mittel"
	Viel   NeuesMitgliedZeit = "viel"
	Wenig  NeuesMitgliedZeit = "wenig"
)

// Valid indicates whether the value is a known member of the NeuesMitgliedZeit enum.
func (e NeuesMitgliedZeit) Valid() bool {
	switch e {
	case Keine:
		return true
	case Mittel:
		return true
	case Viel:
		return true
	case Wenig:
		return true
	default:
		return false
	}
}

// Defines values for UebersprungenGrund.
const (
	Abgewaehlt      UebersprungenGrund = "abgewaehlt"
	GiltNicht       UebersprungenGrund = "gilt_nicht"
	KeineKapazitaet UebersprungenGrund = "keine_kapazitaet"
	NichtFaellig    UebersprungenGrund = "nicht_faellig"
	NiemandGeeignet UebersprungenGrund = "niemand_geeignet"
	Startdichte     UebersprungenGrund = "startdichte"
)

// Valid indicates whether the value is a known member of the UebersprungenGrund enum.
func (e UebersprungenGrund) Valid() bool {
	switch e {
	case Abgewaehlt:
		return true
	case GiltNicht:
		return true
	case KeineKapazitaet:
		return true
	case NichtFaellig:
		return true
	case NiemandGeeignet:
		return true
	case Startdichte:
		return true
	default:
		return false
	}
}

// Defines values for WochenplanMeineRolle.
const (
	WochenplanMeineRolleAusfuehrend WochenplanMeineRolle = "ausfuehrend"
	WochenplanMeineRolleBetreut     WochenplanMeineRolle = "betreut"
	WochenplanMeineRollePlanend     WochenplanMeineRolle = "planend"
)

// Valid indicates whether the value is a known member of the WochenplanMeineRolle enum.
func (e WochenplanMeineRolle) Valid() bool {
	switch e {
	case WochenplanMeineRolleAusfuehrend:
		return true
	case WochenplanMeineRolleBetreut:
		return true
	case WochenplanMeineRollePlanend:
		return true
	default:
		return false
	}
}

// Defines values for CreateEinladungJSONBodyRolle.
const (
	CreateEinladungJSONBodyRolleAusfuehrend CreateEinladungJSONBodyRolle = "ausfuehrend"
	CreateEinladungJSONBodyRollePlanend     CreateEinladungJSONBodyRolle = "planend"
)

// Valid indicates whether the value is a known member of the CreateEinladungJSONBodyRolle enum.
func (e CreateEinladungJSONBodyRolle) Valid() bool {
	switch e {
	case CreateEinladungJSONBodyRolleAusfuehrend:
		return true
	case CreateEinladungJSONBodyRollePlanend:
		return true
	default:
		return false
	}
}

// Aufgabe defines model for Aufgabe.
type Aufgabe struct {
	Art AufgabeArt `json:"art"`

	// Begruendung Maschinenlesbar. Das Sprachmodell formuliert daraus später einen Satz
	// für die Oberfläche — es erfindet keine Begründung, es übersetzt eine.
	Begruendung Begruendung `json:"begruendung"`

	// DauerMin Example: 35
	DauerMin int `json:"dauer_min"`

	// Frist gesetzt, wenn die Aufgabe eine echte Frist hat
	Frist     *string   `json:"frist,omitempty"`
	Kategorie Kategorie `json:"kategorie"`

	// Kopflast Planungs- und Erinnerungsaufwand, unabhängig von der Dauer
	Kopflast int `json:"kopflast"`

	// Tag Kalendertag ohne Uhrzeit und ohne Zeitzone (ADR-0002). Über die
	// Grenze geht die ISO-Zeichenkette; die Anzeige rechnet sie in
	// Europe/Berlin um.
	//
	//
	// Example: 2026-09-19
	Tag string `json:"tag"`

	// Titel Example: Bad putzen
	Titel string `json:"titel"`

	// VorlageId Example: t-bad
	VorlageId   string             `json:"vorlage_id"`
	Zeitfenster AufgabeZeitfenster `json:"zeitfenster"`

	// Zustaendig Kennung des Mitglieds
	//
	// Example: m-ben
	Zustaendig string `json:"zustaendig"`
}

// AufgabeArt defines model for Aufgabe.Art.
type AufgabeArt string

// AufgabeZeitfenster defines model for Aufgabe.Zeitfenster.
type AufgabeZeitfenster string

// Begruendung Maschinenlesbar. Das Sprachmodell formuliert daraus später einen Satz
// für die Oberfläche — es erfindet keine Begründung, es übersetzt eine.
type Begruendung struct {
	Code BegruendungCode `json:"code"`

	// ZuletztBei bei `rotation` die Person, die die Aufgabe zuletzt hatte
	ZuletztBei *string `json:"zuletzt_bei,omitempty"`
}

// BegruendungCode defines model for Begruendung.Code.
type BegruendungCode string

// Bilanz defines model for Bilanz.
type Bilanz struct {
	Aufgaben int `json:"aufgaben"`

	// AuslastungProzent Verplante Minuten im Verhältnis zur verfügbaren Zeit. Gerechnet
	// wird mit den reinen Minuten — Kopflast kostet Aufmerksamkeit,
	// aber keine Uhrzeit (ADR-0004).
	AuslastungProzent int `json:"auslastung_prozent"`

	// Gewichtet Minuten + Kopflast × 15
	Gewichtet int `json:"gewichtet"`

	// KapazitaetMinuten verfügbare Minuten der ganzen Woche
	KapazitaetMinuten int    `json:"kapazitaet_minuten"`
	Kopflast          int    `json:"kopflast"`
	Minuten           int    `json:"minuten"`
	MitgliedId        string `json:"mitglied_id"`
}

// Einladung defines model for Einladung.
type Einladung struct {
	// Code Example: K7MQ2XPD
	Code string `json:"code"`

	// Fuer Name der Person, die dieser Code übernimmt. Fehlt, wenn jemand
	// Neues dazukommt.
	//
	//
	// Example: Asmae
	Fuer       *string        `json:"fuer,omitempty"`
	GueltigBis time.Time      `json:"gueltig_bis"`
	Rolle      EinladungRolle `json:"rolle"`
}

// EinladungRolle defines model for Einladung.Rolle.
type EinladungRolle string

// Fehler defines model for Fehler.
type Fehler struct {
	// Fehler für Menschen lesbar, deutsch
	//
	// Example: die Woche "2026-W99" liegt außerhalb von 1..53
	Fehler string `json:"fehler"`
}

// Haushalt defines model for Haushalt.
type Haushalt struct {
	// Id Example: familie-a
	Id string `json:"id"`

	// MeineRolle Die Rolle des Aufrufers in diesem Haushalt. Fehlt bei den
	// öffentlichen Beispielhaushalten und überall dort, wo er nicht
	// Mitglied ist.
	MeineRolle *HaushaltMeineRolle `json:"meine_rolle,omitempty"`
	Mitglieder []Mitglied          `json:"mitglieder"`

	// Name Example: Familie A
	Name string `json:"name"`
}

// HaushaltMeineRolle Die Rolle des Aufrufers in diesem Haushalt. Fehlt bei den
// öffentlichen Beispielhaushalten und überall dort, wo er nicht
// Mitglied ist.
type HaushaltMeineRolle string

// Ich Absichtlich schmal: Hier steht nur, was der Aussteller signiert hat.
// Welche Person in welchem Haushalt dahintersteckt, ist eine Frage an die
// Datenbank und kommt mit dem Onboarding dazu.
type Ich struct {
	Angemeldet bool    `json:"angemeldet"`
	Email      *string `json:"email,omitempty"`
	Name       *string `json:"name,omitempty"`

	// Subject Nutzerkennung des Anmeldedienstes
	Subject *string `json:"subject,omitempty"`
}

// Kategorie defines model for Kategorie.
type Kategorie string

// Mitglied defines model for Mitglied.
type Mitglied struct {
	// HatZugang Ob diese Person sich anmelden kann. Steuert, wen man noch einladen
	// kann — und macht sichtbar, wer bisher nur im Plan steht.
	HatZugang *bool `json:"hat_zugang,omitempty"`

	// Id Example: m-anna
	Id string `json:"id"`

	// Name Example: Anna
	Name string `json:"name"`

	// Rolle `planend` plant und führt aus, `ausfuehrend` führt nur aus,
	// `betreut` erzeugt Arbeit ohne welche zu übernehmen.
	Rolle MitgliedRolle `json:"rolle"`
}

// MitgliedRolle `planend` plant und führt aus, `ausfuehrend` führt nur aus,
// `betreut` erzeugt Arbeit ohne welche zu übernehmen.
type MitgliedRolle string

// NeuerHaushalt defines model for NeuerHaushalt.
type NeuerHaushalt struct {
	// Auto Entscheidet über Aufgaben wie Reifenwechsel oder TÜV. Fehlt das
	// Auto, entstehen sie gar nicht erst.
	Auto       *bool           `json:"auto,omitempty"`
	Garten     *bool           `json:"garten,omitempty"`
	Haustiere  *[]string       `json:"haustiere,omitempty"`
	Mitglieder []NeuesMitglied `json:"mitglieder"`

	// Name Example: Familie Bauer
	Name     string                `json:"name"`
	Wohnform NeuerHaushaltWohnform `json:"wohnform"`

	// Zeitzone Bestimmt, wann ein Tag beginnt und endet. Siehe ADR-0002.
	Zeitzone *string `json:"zeitzone,omitempty"`
}

// NeuerHaushaltWohnform defines model for NeuerHaushalt.Wohnform.
type NeuerHaushaltWohnform string

// NeuesMitglied defines model for NeuesMitglied.
type NeuesMitglied struct {
	// Geburtsjahr Nur bei Kindern nötig; es entscheidet über Altersgrenzen von
	// Aufgaben. Bei Erwachsenen darf es fehlen — dann gelten sie als
	// erwachsen und mehr braucht der Planer nicht zu wissen.
	Geburtsjahr *int               `json:"geburtsjahr,omitempty"`
	Name        string             `json:"name"`
	Rolle       NeuesMitgliedRolle `json:"rolle"`

	// Zeit Grobes Zeitbudget statt sieben Zahlen. Niemand weiß, wie viele
	// Minuten Haushalt er dienstags hat; eine erfundene Zahl sieht nur
	// präziser aus als eine ehrliche Stufe.
	Zeit *NeuesMitgliedZeit `json:"zeit,omitempty"`
}

// NeuesMitgliedRolle defines model for NeuesMitglied.Rolle.
type NeuesMitgliedRolle string

// NeuesMitgliedZeit Grobes Zeitbudget statt sieben Zahlen. Niemand weiß, wie viele
// Minuten Haushalt er dienstags hat; eine erfundene Zahl sieht nur
// präziser aus als eine ehrliche Stufe.
type NeuesMitgliedZeit string

// Uebersprungen defines model for Uebersprungen.
type Uebersprungen struct {
	Grund     UebersprungenGrund `json:"grund"`
	Titel     string             `json:"titel"`
	VorlageId string             `json:"vorlage_id"`
}

// UebersprungenGrund defines model for Uebersprungen.Grund.
type UebersprungenGrund string

// Version defines model for Version.
type Version struct {
	// Version kurze Commit-Kennung oder "dev"
	//
	// Example: f18a432
	Version string `json:"version"`
}

// Wochenplan defines model for Wochenplan.
type Wochenplan struct {
	Aufgaben []Aufgabe `json:"aufgaben"`

	// Bilanz Eine Zeile je Person, die Aufgaben übernehmen kann — **nur für
	// planende Personen**. Wer ausführt, sieht den ganzen Plan, aber
	// nicht die Auswertung darüber, wer im Haushalt wie viel trägt.
	//
	// Fehlt das Feld, ist das kein Fehler: Der Aufrufer darf es nicht
	// sehen. Demo-Haushalte liefern es mit, sie haben nichts zu
	// verbergen.
	Bilanz   *[]Bilanz `json:"bilanz,omitempty"`
	Haushalt Haushalt  `json:"haushalt"`

	// MeineRolle Die Rolle des Aufrufers in diesem Haushalt. Fehlt bei
	// Demo-Haushalten und ohne Anmeldung.
	MeineRolle *WochenplanMeineRolle `json:"meine_rolle,omitempty"`

	// Uebersprungen Was nicht im Plan steht, mit Grund. Ohne dieses Feld könnte die
	// App nicht erklären, warum etwas fehlt.
	Uebersprungen []Uebersprungen `json:"uebersprungen"`

	// Woche Example: 2026-W38
	Woche string `json:"woche"`
}

// WochenplanMeineRolle Die Rolle des Aufrufers in diesem Haushalt. Fehlt bei
// Demo-Haushalten und ohne Anmeldung.
type WochenplanMeineRolle string

// CreateEinladungJSONBody defines parameters for CreateEinladung.
type CreateEinladungJSONBody struct {
	// Mitglied Kennung einer Person, die schon im Plan steht, aber noch
	// kein Konto hat. Der Code macht den Eingeladenen dann zu
	// genau dieser Person — mit ihren Aufgaben, ihrem Verlauf und
	// ihrer Kapazität, statt eine zweite gleichen Namens
	// anzulegen.
	Mitglied *string `json:"mitglied,omitempty"`

	// Rolle Nötig, wenn jemand dazukommt, den es im Haushalt noch nicht
	// gibt. Zusammen mit `mitglied` wird sie ignoriert: Diese
	// Person hat ihre Rolle bereits, und der Plan rechnet damit.
	Rolle *CreateEinladungJSONBodyRolle `json:"rolle,omitempty"`
}

// CreateEinladungJSONBodyRolle defines parameters for CreateEinladung.
type CreateEinladungJSONBodyRolle string

// CreateHaushaltJSONRequestBody defines body for CreateHaushalt for application/json ContentType.
type CreateHaushaltJSONRequestBody = NeuerHaushalt

// CreateEinladungJSONRequestBody defines body for CreateEinladung for application/json ContentType.
type CreateEinladungJSONRequestBody CreateEinladungJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// AcceptEinladung Einer Einladung folgen
	// (POST /api/einladungen/{code}/annehmen)
	AcceptEinladung(w http.ResponseWriter, r *http.Request, code string)
	// ListHaushalte Verfügbare Haushalte
	// (GET /api/haushalte)
	ListHaushalte(w http.ResponseWriter, r *http.Request)
	// CreateHaushalt Haushalt einrichten
	// (POST /api/haushalte)
	CreateHaushalt(w http.ResponseWriter, r *http.Request)
	// CreateEinladung Jemanden einladen
	// (POST /api/haushalte/{haushaltId}/einladungen)
	CreateEinladung(w http.ResponseWriter, r *http.Request, haushaltId string)
	// GetWochenplan Wochenplan eines Haushalts
	// (GET /api/haushalte/{haushaltId}/plan/{woche})
	GetWochenplan(w http.ResponseWriter, r *http.Request, haushaltId string, woche string)
	// GetIch Wer fragt
	// (GET /api/ich)
	GetIch(w http.ResponseWriter, r *http.Request)
	// GetVersion Welcher Stand läuft gerade
	// (GET /api/version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AcceptEinladung operation middleware
func (siw *ServerInterfaceWrapper) AcceptEinladung(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code string

	err = runtime.BindStyledParameterWithOptions("simple", "code", r.PathValue("code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptEinladung(w, r, code)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHaushalte operation middleware
func (siw *ServerInterfaceWrapper) ListHaushalte(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHaushalte(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateHaushalt operation middleware
func (siw *ServerInterfaceWrapper) CreateHaushalt(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateHaushalt(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEinladung operation middleware
func (siw *ServerInterfaceWrapper) CreateEinladung(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "haushaltId" -------------
	var haushaltId string

	err = runtime.BindStyledParameterWithOptions("simple", "haushaltId", r.PathValue("haushaltId"), &haushaltId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "haushaltId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEinladung(w, r, haushaltId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWochenplan operation middleware
func (siw *ServerInterfaceWrapper) GetWochenplan(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "haushaltId" -------------
	var haushaltId string

	err = runtime.BindStyledParameterWithOptions("simple", "haushaltId", r.PathValue("haushaltId"), &haushaltId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "haushaltId", Err: err})
		return
	}

	// ------------- Path parameter "woche" -------------
	var woche string

	err = runtime.BindStyledParameterWithOptions("simple", "woche", r.PathValue("woche"), &woche, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "woche", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWochenplan(w, r, haushaltId, woche)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIch operation middleware
func (siw *ServerInterfaceWrapper) GetIch(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/version", wrapper.GetVersion)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/ich", wrapper.GetIch)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/haushalte", wrapper.ListHaushalte)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/haushalte", wrapper.CreateHaushalt)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/haushalte/{haushaltId}/plan/{woche}", wrapper.GetWochenplan)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/haushalte/{haushaltId}/einladungen", wrapper.CreateEinladung)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/einladungen/{code}/annehmen", wrapper.AcceptEinladung)

	return m
}

type AcceptEinladungRequestObject struct {
	Code string `json:"code"`
}

type AcceptEinladungResponseObject interface {
	VisitAcceptEinladungResponse(w http.ResponseWriter) error
}

type AcceptEinladung200JSONResponse Haushalt

func (response AcceptEinladung200JSONResponse) VisitAcceptEinladungResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptEinladung401JSONResponse Fehler

func (response AcceptEinladung401JSONResponse) VisitAcceptEinladungResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptEinladung404JSONResponse Fehler

func (response AcceptEinladung404JSONResponse) VisitAcceptEinladungResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListHaushalteRequestObject struct {
}

type ListHaushalteResponseObject interface {
	VisitListHaushalteResponse(w http.ResponseWriter) error
}

type ListHaushalte200JSONResponse []Haushalt

func (response ListHaushalte200JSONResponse) VisitListHaushalteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateHaushaltRequestObject struct {
	Body *CreateHaushaltJSONRequestBody
}

type CreateHaushaltResponseObject interface {
	VisitCreateHaushaltResponse(w http.ResponseWriter) error
}

type CreateHaushalt201JSONResponse Haushalt

func (response CreateHaushalt201JSONResponse) VisitCreateHaushaltResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateHaushalt400JSONResponse Fehler

func (response CreateHaushalt400JSONResponse) VisitCreateHaushaltResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateHaushalt401JSONResponse Fehler

func (response CreateHaushalt401JSONResponse) VisitCreateHaushaltResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEinladungRequestObject struct {
	HaushaltId string `json:"haushaltId"`
	Body       *CreateEinladungJSONRequestBody
}

type CreateEinladungResponseObject interface {
	VisitCreateEinladungResponse(w http.ResponseWriter) error
}

type CreateEinladung201JSONResponse Einladung

func (response CreateEinladung201JSONResponse) VisitCreateEinladungResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEinladung403JSONResponse Fehler

func (response CreateEinladung403JSONResponse) VisitCreateEinladungResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEinladung404JSONResponse Fehler

func (response CreateEinladung404JSONResponse) VisitCreateEinladungResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetWochenplanRequestObject struct {
	HaushaltId string `json:"haushaltId"`
	Woche      string `json:"woche"`
}

type GetWochenplanResponseObject interface {
	VisitGetWochenplanResponse(w http.ResponseWriter) error
}

type GetWochenplan200JSONResponse Wochenplan

func (response GetWochenplan200JSONResponse) VisitGetWochenplanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetWochenplan400JSONResponse Fehler

func (response GetWochenplan400JSONResponse) VisitGetWochenplanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetWochenplan404JSONResponse Fehler

func (response GetWochenplan404JSONResponse) VisitGetWochenplanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetIchRequestObject struct {
}

type GetIchResponseObject interface {
	VisitGetIchResponse(w http.ResponseWriter) error
}

type GetIch200JSONResponse Ich

func (response GetIch200JSONResponse) VisitGetIchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse Version

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// AcceptEinladung Einer Einladung folgen
	// (POST /api/einladungen/{code}/annehmen)
	AcceptEinladung(ctx context.Context, request AcceptEinladungRequestObject) (AcceptEinladungResponseObject, error)
	// ListHaushalte Verfügbare Haushalte
	// (GET /api/haushalte)
	ListHaushalte(ctx context.Context, request ListHaushalteRequestObject) (ListHaushalteResponseObject, error)
	// CreateHaushalt Haushalt einrichten
	// (POST /api/haushalte)
	CreateHaushalt(ctx context.Context, request CreateHaushaltRequestObject) (CreateHaushaltResponseObject, error)
	// CreateEinladung Jemanden einladen
	// (POST /api/haushalte/{haushaltId}/einladungen)
	CreateEinladung(ctx context.Context, request CreateEinladungRequestObject) (CreateEinladungResponseObject, error)
	// GetWochenplan Wochenplan eines Haushalts
	// (GET /api/haushalte/{haushaltId}/plan/{woche})
	GetWochenplan(ctx context.Context, request GetWochenplanRequestObject) (GetWochenplanResponseObject, error)
	// GetIch Wer fragt
	// (GET /api/ich)
	GetIch(ctx context.Context, request GetIchRequestObject) (GetIchResponseObject, error)
	// GetVersion Welcher Stand läuft gerade
	// (GET /api/version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AcceptEinladung operation middleware
func (sh *strictHandler) AcceptEinladung(w http.ResponseWriter, r *http.Request, code string) {
	var request AcceptEinladungRequestObject

	request.Code = code

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AcceptEinladung(ctx, request.(AcceptEinladungRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AcceptEinladung")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AcceptEinladungResponseObject); ok {
		if err := validResponse.VisitAcceptEinladungResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListHaushalte operation middleware
func (sh *strictHandler) ListHaushalte(w http.ResponseWriter, r *http.Request) {
	var request ListHaushalteRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListHaushalte(ctx, request.(ListHaushalteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListHaushalte")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListHaushalteResponseObject); ok {
		if err := validResponse.VisitListHaushalteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateHaushalt operation middleware
func (sh *strictHandler) CreateHaushalt(w http.ResponseWriter, r *http.Request) {
	var request CreateHaushaltRequestObject

	var body CreateHaushaltJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateHaushalt(ctx, request.(CreateHaushaltRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateHaushalt")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateHaushaltResponseObject); ok {
		if err := validResponse.VisitCreateHaushaltResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEinladung operation middleware
func (sh *strictHandler) CreateEinladung(w http.ResponseWriter, r *http.Request, haushaltId string) {
	var request CreateEinladungRequestObject

	request.HaushaltId = haushaltId

	var body CreateEinladungJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEinladung(ctx, request.(CreateEinladungRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEinladung")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEinladungResponseObject); ok {
		if err := validResponse.VisitCreateEinladungResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWochenplan operation middleware
func (sh *strictHandler) GetWochenplan(w http.ResponseWriter, r *http.Request, haushaltId string, woche string) {
	var request GetWochenplanRequestObject

	request.HaushaltId = haushaltId
	request.Woche = woche

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWochenplan(ctx, request.(GetWochenplanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWochenplan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWochenplanResponseObject); ok {
		if err := validResponse.VisitGetWochenplanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetIch operation middleware
func (sh *strictHandler) GetIch(w http.ResponseWriter, r *http.Request) {
	var request GetIchRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetIch(ctx, request.(GetIchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetIchResponseObject); ok {
		if err := validResponse.VisitGetIchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request) {
	var request GetVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
